// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoAppsColumns holds the columns for the "co_apps" table.
	CoAppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "app_id", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "description", Type: field.TypeBytes},
		{Name: "digest", Type: field.TypeString},
	}
	// CoAppsTable holds the schema information for the "co_apps" table.
	CoAppsTable = &schema.Table{
		Name:       "co_apps",
		Columns:    CoAppsColumns,
		PrimaryKey: []*schema.Column{CoAppsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "co_apps_app_id_version",
				Unique:  true,
				Columns: []*schema.Column{CoAppsColumns[1], CoAppsColumns[2]},
			},
		},
	}
	// CoBlobsColumns holds the columns for the "co_blobs" table.
	CoBlobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "content", Type: field.TypeBytes},
	}
	// CoBlobsTable holds the schema information for the "co_blobs" table.
	CoBlobsTable = &schema.Table{
		Name:       "co_blobs",
		Columns:    CoBlobsColumns,
		PrimaryKey: []*schema.Column{CoBlobsColumns[0]},
	}
	// CoDeploymentsColumns holds the columns for the "co_deployments" table.
	CoDeploymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "target", Type: field.TypeString},
		{Name: "app_id", Type: field.TypeString},
		{Name: "app_version", Type: field.TypeString},
		{Name: "profile", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "namespace", Type: field.TypeString},
		{Name: "parameters", Type: field.TypeBytes},
		{Name: "digest", Type: field.TypeString},
		{Name: "digest_version", Type: field.TypeUint64},
		{Name: "deleted", Type: field.TypeBool},
		{Name: "deleted_version", Type: field.TypeUint64},
		{Name: "removed", Type: field.TypeBool},
		{Name: "reported", Type: field.TypeBool, Default: false},
		{Name: "current_status", Type: field.TypeBytes, Nullable: true},
		{Name: "site_id", Type: field.TypeString},
	}
	// CoDeploymentsTable holds the schema information for the "co_deployments" table.
	CoDeploymentsTable = &schema.Table{
		Name:       "co_deployments",
		Columns:    CoDeploymentsColumns,
		PrimaryKey: []*schema.Column{CoDeploymentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "co_deployments_co_sites_deployments",
				Columns:    []*schema.Column{CoDeploymentsColumns[15]},
				RefColumns: []*schema.Column{CoSitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "co_deployments_site_id",
				Unique:  false,
				Columns: []*schema.Column{CoDeploymentsColumns[15]},
			},
		},
	}
	// CoDevicesColumns holds the columns for the "co_devices" table.
	CoDevicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString},
		{Name: "capabilities", Type: field.TypeBytes},
		{Name: "site_id", Type: field.TypeString},
	}
	// CoDevicesTable holds the schema information for the "co_devices" table.
	CoDevicesTable = &schema.Table{
		Name:       "co_devices",
		Columns:    CoDevicesColumns,
		PrimaryKey: []*schema.Column{CoDevicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "co_devices_co_sites_devices",
				Columns:    []*schema.Column{CoDevicesColumns[3]},
				RefColumns: []*schema.Column{CoSitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "co_devices_site_id_host",
				Unique:  true,
				Columns: []*schema.Column{CoDevicesColumns[3], CoDevicesColumns[1]},
			},
		},
	}
	// CoPublicationsColumns holds the columns for the "co_publications" table.
	CoPublicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "bundle", Type: field.TypeBool},
		{Name: "deployment_id", Type: field.TypeUUID},
		{Name: "digest", Type: field.TypeString},
		{Name: "site_id", Type: field.TypeString},
	}
	// CoPublicationsTable holds the schema information for the "co_publications" table.
	CoPublicationsTable = &schema.Table{
		Name:       "co_publications",
		Columns:    CoPublicationsColumns,
		PrimaryKey: []*schema.Column{CoPublicationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "co_publications_co_sites_publications",
				Columns:    []*schema.Column{CoPublicationsColumns[4]},
				RefColumns: []*schema.Column{CoSitesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "co_publications_key",
				Unique:  true,
				Columns: []*schema.Column{CoPublicationsColumns[4], CoPublicationsColumns[1], CoPublicationsColumns[2], CoPublicationsColumns[3]},
			},
		},
	}
	// CoSitesColumns holds the columns for the "co_sites" table.
	CoSitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "retired", Type: field.TypeBool, Default: false},
		{Name: "manifest_version", Type: field.TypeUint64, Default: 0},
		{Name: "manifest_body", Type: field.TypeBytes, Nullable: true},
		{Name: "manifest_etag", Type: field.TypeString, Default: ""},
		{Name: "manifest_bundle", Type: field.TypeString, Default: ""},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true, Nullable: true},
	}
	// CoSitesTable holds the schema information for the "co_sites" table.
	CoSitesTable = &schema.Table{
		Name:       "co_sites",
		Columns:    CoSitesColumns,
		PrimaryKey: []*schema.Column{CoSitesColumns[0]},
	}
	// CoStatusesColumns holds the columns for the "co_statuses" table.
	CoStatusesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeBytes},
		{Name: "deployment_id", Type: field.TypeUUID},
	}
	// CoStatusesTable holds the schema information for the "co_statuses" table.
	CoStatusesTable = &schema.Table{
		Name:       "co_statuses",
		Columns:    CoStatusesColumns,
		PrimaryKey: []*schema.Column{CoStatusesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "co_statuses_co_deployments_statuses",
				Columns:    []*schema.Column{CoStatusesColumns[2]},
				RefColumns: []*schema.Column{CoDeploymentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "co_statuses_deployment_id",
				Unique:  false,
				Columns: []*schema.Column{CoStatusesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoAppsTable,
		CoBlobsTable,
		CoDeploymentsTable,
		CoDevicesTable,
		CoPublicationsTable,
		CoSitesTable,
		CoStatusesTable,
	}
)

func init() {
	CoAppsTable.Annotation = &entsql.Annotation{
		Table: "co_apps",
	}
	CoBlobsTable.Annotation = &entsql.Annotation{
		Table: "co_blobs",
	}
	CoDeploymentsTable.ForeignKeys[0].RefTable = CoSitesTable
	CoDeploymentsTable.Annotation = &entsql.Annotation{
		Table: "co_deployments",
	}
	CoDevicesTable.ForeignKeys[0].RefTable = CoSitesTable
	CoDevicesTable.Annotation = &entsql.Annotation{
		Table: "co_devices",
	}
	CoPublicationsTable.ForeignKeys[0].RefTable = CoSitesTable
	CoPublicationsTable.Annotation = &entsql.Annotation{
		Table: "co_publications",
	}
	CoSitesTable.Annotation = &entsql.Annotation{
		Table: "co_sites",
	}
	CoStatusesTable.ForeignKeys[0].RefTable = CoDeploymentsTable
	CoStatusesTable.Annotation = &entsql.Annotation{
		Table: "co_statuses",
	}
}
