// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
	"github.com/google/uuid"
)

// Deployment is the model entity for the Deployment schema.
type Deployment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID string `json:"site_id,omitempty"`
	// Target holds the value of the "target" field.
	Target string `json:"target,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// AppVersion holds the value of the "app_version" field.
	AppVersion string `json:"app_version,omitempty"`
	// Profile holds the value of the "profile" field.
	Profile string `json:"profile,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Namespace holds the value of the "namespace" field.
	Namespace string `json:"namespace,omitempty"`
	// Parameters holds the value of the "parameters" field.
	Parameters []byte `json:"parameters,omitempty"`
	// Digest holds the value of the "digest" field.
	Digest string `json:"digest,omitempty"`
	// DigestVersion holds the value of the "digest_version" field.
	DigestVersion uint64 `json:"digest_version,omitempty"`
	// Deleted holds the value of the "deleted" field.
	Deleted bool `json:"deleted,omitempty"`
	// DeletedVersion holds the value of the "deleted_version" field.
	DeletedVersion uint64 `json:"deleted_version,omitempty"`
	// Removed holds the value of the "removed" field.
	Removed bool `json:"removed,omitempty"`
	// Reported holds the value of the "reported" field.
	Reported bool `json:"reported,omitempty"`
	// CurrentStatus holds the value of the "current_status" field.
	CurrentStatus *[]byte `json:"current_status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeploymentQuery when eager-loading is set.
	Edges        DeploymentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeploymentEdges holds the relations/edges for other nodes in the graph.
type DeploymentEdges struct {
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// Statuses holds the value of the statuses edge.
	Statuses []*Status `json:"statuses,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DeploymentEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// StatusesOrErr returns the Statuses value or an error if the edge
// was not loaded in eager-loading.
func (e DeploymentEdges) StatusesOrErr() ([]*Status, error) {
	if e.loadedTypes[1] {
		return e.Statuses, nil
	}
	return nil, &NotLoadedError{edge: "statuses"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deployment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deployment.FieldParameters, deployment.FieldCurrentStatus:
			values[i] = new([]byte)
		case deployment.FieldDeleted, deployment.FieldRemoved, deployment.FieldReported:
			values[i] = new(sql.NullBool)
		case deployment.FieldDigestVersion, deployment.FieldDeletedVersion:
			values[i] = new(sql.NullInt64)
		case deployment.FieldSiteID, deployment.FieldTarget, deployment.FieldAppID, deployment.FieldAppVersion, deployment.FieldProfile, deployment.FieldName, deployment.FieldNamespace, deployment.FieldDigest:
			values[i] = new(sql.NullString)
		case deployment.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deployment fields.
func (_m *Deployment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deployment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deployment.FieldSiteID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value.Valid {
				_m.SiteID = value.String
			}
		case deployment.FieldTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target", values[i])
			} else if value.Valid {
				_m.Target = value.String
			}
		case deployment.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case deployment.FieldAppVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_version", values[i])
			} else if value.Valid {
				_m.AppVersion = value.String
			}
		case deployment.FieldProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile", values[i])
			} else if value.Valid {
				_m.Profile = value.String
			}
		case deployment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case deployment.FieldNamespace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field namespace", values[i])
			} else if value.Valid {
				_m.Namespace = value.String
			}
		case deployment.FieldParameters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field parameters", values[i])
			} else if value != nil {
				_m.Parameters = *value
			}
		case deployment.FieldDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field digest", values[i])
			} else if value.Valid {
				_m.Digest = value.String
			}
		case deployment.FieldDigestVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field digest_version", values[i])
			} else if value.Valid {
				_m.DigestVersion = uint64(value.Int64)
			}
		case deployment.FieldDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field deleted", values[i])
			} else if value.Valid {
				_m.Deleted = value.Bool
			}
		case deployment.FieldDeletedVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_version", values[i])
			} else if value.Valid {
				_m.DeletedVersion = uint64(value.Int64)
			}
		case deployment.FieldRemoved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field removed", values[i])
			} else if value.Valid {
				_m.Removed = value.Bool
			}
		case deployment.FieldReported:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field reported", values[i])
			} else if value.Valid {
				_m.Reported = value.Bool
			}
		case deployment.FieldCurrentStatus:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field current_status", values[i])
			} else if value != nil {
				_m.CurrentStatus = value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deployment.
// This includes values selected through modifiers, order, etc.
func (_m *Deployment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySite queries the "site" edge of the Deployment entity.
func (_m *Deployment) QuerySite() *SiteQuery {
	return NewDeploymentClient(_m.config).QuerySite(_m)
}

// QueryStatuses queries the "statuses" edge of the Deployment entity.
func (_m *Deployment) QueryStatuses() *StatusQuery {
	return NewDeploymentClient(_m.config).QueryStatuses(_m)
}

// Update returns a builder for updating this Deployment.
// Note that you need to call Deployment.Unwrap() before calling this method if this Deployment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deployment) Update() *DeploymentUpdateOne {
	return NewDeploymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deployment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deployment) Unwrap() *Deployment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Deployment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deployment) String() string {
	var builder strings.Builder
	builder.WriteString("Deployment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("site_id=")
	builder.WriteString(_m.SiteID)
	builder.WriteString(", ")
	builder.WriteString("target=")
	builder.WriteString(_m.Target)
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("app_version=")
	builder.WriteString(_m.AppVersion)
	builder.WriteString(", ")
	builder.WriteString("profile=")
	builder.WriteString(_m.Profile)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("namespace=")
	builder.WriteString(_m.Namespace)
	builder.WriteString(", ")
	builder.WriteString("parameters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Parameters))
	builder.WriteString(", ")
	builder.WriteString("digest=")
	builder.WriteString(_m.Digest)
	builder.WriteString(", ")
	builder.WriteString("digest_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.DigestVersion))
	builder.WriteString(", ")
	builder.WriteString("deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deleted))
	builder.WriteString(", ")
	builder.WriteString("deleted_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedVersion))
	builder.WriteString(", ")
	builder.WriteString("removed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Removed))
	builder.WriteString(", ")
	builder.WriteString("reported=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reported))
	builder.WriteString(", ")
	if v := _m.CurrentStatus; v != nil {
		builder.WriteString("current_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Deployments is a parsable slice of Deployment.
type Deployments []*Deployment
