// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/status"
)

// DeploymentUpdate is the builder for updating Deployment entities.
type DeploymentUpdate struct {
	config
	hooks    []Hook
	mutation *DeploymentMutation
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdate) Where(ps ...predicate.Deployment) *DeploymentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTarget sets the "target" field.
func (_u *DeploymentUpdate) SetTarget(v string) *DeploymentUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableTarget(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *DeploymentUpdate) SetAppID(v string) *DeploymentUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableAppID(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeploymentUpdate) SetAppVersion(v string) *DeploymentUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableAppVersion(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetProfile sets the "profile" field.
func (_u *DeploymentUpdate) SetProfile(v string) *DeploymentUpdate {
	_u.mutation.SetProfile(v)
	return _u
}

// SetNillableProfile sets the "profile" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableProfile(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetProfile(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeploymentUpdate) SetName(v string) *DeploymentUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableName(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *DeploymentUpdate) SetNamespace(v string) *DeploymentUpdate {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableNamespace(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *DeploymentUpdate) SetParameters(v []byte) *DeploymentUpdate {
	_u.mutation.SetParameters(v)
	return _u
}

// SetDigest sets the "digest" field.
func (_u *DeploymentUpdate) SetDigest(v string) *DeploymentUpdate {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableDigest(v *string) *DeploymentUpdate {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// SetDigestVersion sets the "digest_version" field.
func (_u *DeploymentUpdate) SetDigestVersion(v uint64) *DeploymentUpdate {
	_u.mutation.ResetDigestVersion()
	_u.mutation.SetDigestVersion(v)
	return _u
}

// SetNillableDigestVersion sets the "digest_version" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableDigestVersion(v *uint64) *DeploymentUpdate {
	if v != nil {
		_u.SetDigestVersion(*v)
	}
	return _u
}

// AddDigestVersion adds value to the "digest_version" field.
func (_u *DeploymentUpdate) AddDigestVersion(v int64) *DeploymentUpdate {
	_u.mutation.AddDigestVersion(v)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *DeploymentUpdate) SetDeleted(v bool) *DeploymentUpdate {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableDeleted(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetDeletedVersion sets the "deleted_version" field.
func (_u *DeploymentUpdate) SetDeletedVersion(v uint64) *DeploymentUpdate {
	_u.mutation.ResetDeletedVersion()
	_u.mutation.SetDeletedVersion(v)
	return _u
}

// SetNillableDeletedVersion sets the "deleted_version" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableDeletedVersion(v *uint64) *DeploymentUpdate {
	if v != nil {
		_u.SetDeletedVersion(*v)
	}
	return _u
}

// AddDeletedVersion adds value to the "deleted_version" field.
func (_u *DeploymentUpdate) AddDeletedVersion(v int64) *DeploymentUpdate {
	_u.mutation.AddDeletedVersion(v)
	return _u
}

// SetRemoved sets the "removed" field.
func (_u *DeploymentUpdate) SetRemoved(v bool) *DeploymentUpdate {
	_u.mutation.SetRemoved(v)
	return _u
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableRemoved(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetRemoved(*v)
	}
	return _u
}

// SetReported sets the "reported" field.
func (_u *DeploymentUpdate) SetReported(v bool) *DeploymentUpdate {
	_u.mutation.SetReported(v)
	return _u
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_u *DeploymentUpdate) SetNillableReported(v *bool) *DeploymentUpdate {
	if v != nil {
		_u.SetReported(*v)
	}
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *DeploymentUpdate) SetCurrentStatus(v []byte) *DeploymentUpdate {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (_u *DeploymentUpdate) ClearCurrentStatus() *DeploymentUpdate {
	_u.mutation.ClearCurrentStatus()
	return _u
}

// AddStatusIDs adds the "statuses" edge to the Status entity by IDs.
func (_u *DeploymentUpdate) AddStatusIDs(ids ...int) *DeploymentUpdate {
	_u.mutation.AddStatusIDs(ids...)
	return _u
}

// AddStatuses adds the "statuses" edges to the Status entity.
func (_u *DeploymentUpdate) AddStatuses(v ...*Status) *DeploymentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusIDs(ids...)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdate) Mutation() *DeploymentMutation {
	return _u.mutation
}

// ClearStatuses clears all "statuses" edges to the Status entity.
func (_u *DeploymentUpdate) ClearStatuses() *DeploymentUpdate {
	_u.mutation.ClearStatuses()
	return _u
}

// RemoveStatusIDs removes the "statuses" edge to Status entities by IDs.
func (_u *DeploymentUpdate) RemoveStatusIDs(ids ...int) *DeploymentUpdate {
	_u.mutation.RemoveStatusIDs(ids...)
	return _u
}

// RemoveStatuses removes "statuses" edges to Status entities.
func (_u *DeploymentUpdate) RemoveStatuses(v ...*Status) *DeploymentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdate) check() error {
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.site"`)
	}
	return nil
}

func (_u *DeploymentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(deployment.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(deployment.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(deployment.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(deployment.FieldProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deployment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(deployment.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(deployment.FieldParameters, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(deployment.FieldDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.DigestVersion(); ok {
		_spec.SetField(deployment.FieldDigestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDigestVersion(); ok {
		_spec.AddField(deployment.FieldDigestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(deployment.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedVersion(); ok {
		_spec.SetField(deployment.FieldDeletedVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDeletedVersion(); ok {
		_spec.AddField(deployment.FieldDeletedVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Removed(); ok {
		_spec.SetField(deployment.FieldRemoved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reported(); ok {
		_spec.SetField(deployment.FieldReported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(deployment.FieldCurrentStatus, field.TypeBytes, value)
	}
	if _u.mutation.CurrentStatusCleared() {
		_spec.ClearField(deployment.FieldCurrentStatus, field.TypeBytes)
	}
	if _u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusesIDs(); len(nodes) > 0 && !_u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentUpdateOne is the builder for updating a single Deployment entity.
type DeploymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeploymentMutation
}

// SetTarget sets the "target" field.
func (_u *DeploymentUpdateOne) SetTarget(v string) *DeploymentUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableTarget(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *DeploymentUpdateOne) SetAppID(v string) *DeploymentUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableAppID(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DeploymentUpdateOne) SetAppVersion(v string) *DeploymentUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableAppVersion(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetProfile sets the "profile" field.
func (_u *DeploymentUpdateOne) SetProfile(v string) *DeploymentUpdateOne {
	_u.mutation.SetProfile(v)
	return _u
}

// SetNillableProfile sets the "profile" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableProfile(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetProfile(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeploymentUpdateOne) SetName(v string) *DeploymentUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableName(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNamespace sets the "namespace" field.
func (_u *DeploymentUpdateOne) SetNamespace(v string) *DeploymentUpdateOne {
	_u.mutation.SetNamespace(v)
	return _u
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableNamespace(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetNamespace(*v)
	}
	return _u
}

// SetParameters sets the "parameters" field.
func (_u *DeploymentUpdateOne) SetParameters(v []byte) *DeploymentUpdateOne {
	_u.mutation.SetParameters(v)
	return _u
}

// SetDigest sets the "digest" field.
func (_u *DeploymentUpdateOne) SetDigest(v string) *DeploymentUpdateOne {
	_u.mutation.SetDigest(v)
	return _u
}

// SetNillableDigest sets the "digest" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableDigest(v *string) *DeploymentUpdateOne {
	if v != nil {
		_u.SetDigest(*v)
	}
	return _u
}

// SetDigestVersion sets the "digest_version" field.
func (_u *DeploymentUpdateOne) SetDigestVersion(v uint64) *DeploymentUpdateOne {
	_u.mutation.ResetDigestVersion()
	_u.mutation.SetDigestVersion(v)
	return _u
}

// SetNillableDigestVersion sets the "digest_version" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableDigestVersion(v *uint64) *DeploymentUpdateOne {
	if v != nil {
		_u.SetDigestVersion(*v)
	}
	return _u
}

// AddDigestVersion adds value to the "digest_version" field.
func (_u *DeploymentUpdateOne) AddDigestVersion(v int64) *DeploymentUpdateOne {
	_u.mutation.AddDigestVersion(v)
	return _u
}

// SetDeleted sets the "deleted" field.
func (_u *DeploymentUpdateOne) SetDeleted(v bool) *DeploymentUpdateOne {
	_u.mutation.SetDeleted(v)
	return _u
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableDeleted(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetDeleted(*v)
	}
	return _u
}

// SetDeletedVersion sets the "deleted_version" field.
func (_u *DeploymentUpdateOne) SetDeletedVersion(v uint64) *DeploymentUpdateOne {
	_u.mutation.ResetDeletedVersion()
	_u.mutation.SetDeletedVersion(v)
	return _u
}

// SetNillableDeletedVersion sets the "deleted_version" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableDeletedVersion(v *uint64) *DeploymentUpdateOne {
	if v != nil {
		_u.SetDeletedVersion(*v)
	}
	return _u
}

// AddDeletedVersion adds value to the "deleted_version" field.
func (_u *DeploymentUpdateOne) AddDeletedVersion(v int64) *DeploymentUpdateOne {
	_u.mutation.AddDeletedVersion(v)
	return _u
}

// SetRemoved sets the "removed" field.
func (_u *DeploymentUpdateOne) SetRemoved(v bool) *DeploymentUpdateOne {
	_u.mutation.SetRemoved(v)
	return _u
}

// SetNillableRemoved sets the "removed" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableRemoved(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetRemoved(*v)
	}
	return _u
}

// SetReported sets the "reported" field.
func (_u *DeploymentUpdateOne) SetReported(v bool) *DeploymentUpdateOne {
	_u.mutation.SetReported(v)
	return _u
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_u *DeploymentUpdateOne) SetNillableReported(v *bool) *DeploymentUpdateOne {
	if v != nil {
		_u.SetReported(*v)
	}
	return _u
}

// SetCurrentStatus sets the "current_status" field.
func (_u *DeploymentUpdateOne) SetCurrentStatus(v []byte) *DeploymentUpdateOne {
	_u.mutation.SetCurrentStatus(v)
	return _u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (_u *DeploymentUpdateOne) ClearCurrentStatus() *DeploymentUpdateOne {
	_u.mutation.ClearCurrentStatus()
	return _u
}

// AddStatusIDs adds the "statuses" edge to the Status entity by IDs.
func (_u *DeploymentUpdateOne) AddStatusIDs(ids ...int) *DeploymentUpdateOne {
	_u.mutation.AddStatusIDs(ids...)
	return _u
}

// AddStatuses adds the "statuses" edges to the Status entity.
func (_u *DeploymentUpdateOne) AddStatuses(v ...*Status) *DeploymentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStatusIDs(ids...)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_u *DeploymentUpdateOne) Mutation() *DeploymentMutation {
	return _u.mutation
}

// ClearStatuses clears all "statuses" edges to the Status entity.
func (_u *DeploymentUpdateOne) ClearStatuses() *DeploymentUpdateOne {
	_u.mutation.ClearStatuses()
	return _u
}

// RemoveStatusIDs removes the "statuses" edge to Status entities by IDs.
func (_u *DeploymentUpdateOne) RemoveStatusIDs(ids ...int) *DeploymentUpdateOne {
	_u.mutation.RemoveStatusIDs(ids...)
	return _u
}

// RemoveStatuses removes "statuses" edges to Status entities.
func (_u *DeploymentUpdateOne) RemoveStatuses(v ...*Status) *DeploymentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStatusIDs(ids...)
}

// Where appends a list predicates to the DeploymentUpdate builder.
func (_u *DeploymentUpdateOne) Where(ps ...predicate.Deployment) *DeploymentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentUpdateOne) Select(field string, fields ...string) *DeploymentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deployment entity.
func (_u *DeploymentUpdateOne) Save(ctx context.Context) (*Deployment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentUpdateOne) SaveX(ctx context.Context) *Deployment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeploymentUpdateOne) check() error {
	if _u.mutation.SiteCleared() && len(_u.mutation.SiteIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Deployment.site"`)
	}
	return nil
}

func (_u *DeploymentUpdateOne) sqlSave(ctx context.Context) (_node *Deployment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deployment.Table, deployment.Columns, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Deployment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deployment.FieldID)
		for _, f := range fields {
			if !deployment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deployment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(deployment.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(deployment.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(deployment.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Profile(); ok {
		_spec.SetField(deployment.FieldProfile, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(deployment.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Namespace(); ok {
		_spec.SetField(deployment.FieldNamespace, field.TypeString, value)
	}
	if value, ok := _u.mutation.Parameters(); ok {
		_spec.SetField(deployment.FieldParameters, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Digest(); ok {
		_spec.SetField(deployment.FieldDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.DigestVersion(); ok {
		_spec.SetField(deployment.FieldDigestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDigestVersion(); ok {
		_spec.AddField(deployment.FieldDigestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Deleted(); ok {
		_spec.SetField(deployment.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DeletedVersion(); ok {
		_spec.SetField(deployment.FieldDeletedVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDeletedVersion(); ok {
		_spec.AddField(deployment.FieldDeletedVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Removed(); ok {
		_spec.SetField(deployment.FieldRemoved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reported(); ok {
		_spec.SetField(deployment.FieldReported, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CurrentStatus(); ok {
		_spec.SetField(deployment.FieldCurrentStatus, field.TypeBytes, value)
	}
	if _u.mutation.CurrentStatusCleared() {
		_spec.ClearField(deployment.FieldCurrentStatus, field.TypeBytes)
	}
	if _u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatusesIDs(); len(nodes) > 0 && !_u.mutation.StatusesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deployment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deployment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
