// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/status"
	"github.com/google/uuid"
)

// DeploymentCreate is the builder for creating a Deployment entity.
type DeploymentCreate struct {
	config
	mutation *DeploymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSiteID sets the "site_id" field.
func (_c *DeploymentCreate) SetSiteID(v string) *DeploymentCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *DeploymentCreate) SetTarget(v string) *DeploymentCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *DeploymentCreate) SetAppID(v string) *DeploymentCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetAppVersion sets the "app_version" field.
func (_c *DeploymentCreate) SetAppVersion(v string) *DeploymentCreate {
	_c.mutation.SetAppVersion(v)
	return _c
}

// SetProfile sets the "profile" field.
func (_c *DeploymentCreate) SetProfile(v string) *DeploymentCreate {
	_c.mutation.SetProfile(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DeploymentCreate) SetName(v string) *DeploymentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNamespace sets the "namespace" field.
func (_c *DeploymentCreate) SetNamespace(v string) *DeploymentCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetParameters sets the "parameters" field.
func (_c *DeploymentCreate) SetParameters(v []byte) *DeploymentCreate {
	_c.mutation.SetParameters(v)
	return _c
}

// SetDigest sets the "digest" field.
func (_c *DeploymentCreate) SetDigest(v string) *DeploymentCreate {
	_c.mutation.SetDigest(v)
	return _c
}

// SetDigestVersion sets the "digest_version" field.
func (_c *DeploymentCreate) SetDigestVersion(v uint64) *DeploymentCreate {
	_c.mutation.SetDigestVersion(v)
	return _c
}

// SetDeleted sets the "deleted" field.
func (_c *DeploymentCreate) SetDeleted(v bool) *DeploymentCreate {
	_c.mutation.SetDeleted(v)
	return _c
}

// SetDeletedVersion sets the "deleted_version" field.
func (_c *DeploymentCreate) SetDeletedVersion(v uint64) *DeploymentCreate {
	_c.mutation.SetDeletedVersion(v)
	return _c
}

// SetRemoved sets the "removed" field.
func (_c *DeploymentCreate) SetRemoved(v bool) *DeploymentCreate {
	_c.mutation.SetRemoved(v)
	return _c
}

// SetReported sets the "reported" field.
func (_c *DeploymentCreate) SetReported(v bool) *DeploymentCreate {
	_c.mutation.SetReported(v)
	return _c
}

// SetNillableReported sets the "reported" field if the given value is not nil.
func (_c *DeploymentCreate) SetNillableReported(v *bool) *DeploymentCreate {
	if v != nil {
		_c.SetReported(*v)
	}
	return _c
}

// SetCurrentStatus sets the "current_status" field.
func (_c *DeploymentCreate) SetCurrentStatus(v []byte) *DeploymentCreate {
	_c.mutation.SetCurrentStatus(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DeploymentCreate) SetID(v uuid.UUID) *DeploymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSite sets the "site" edge to the Site entity.
func (_c *DeploymentCreate) SetSite(v *Site) *DeploymentCreate {
	return _c.SetSiteID(v.ID)
}

// AddStatusIDs adds the "statuses" edge to the Status entity by IDs.
func (_c *DeploymentCreate) AddStatusIDs(ids ...int) *DeploymentCreate {
	_c.mutation.AddStatusIDs(ids...)
	return _c
}

// AddStatuses adds the "statuses" edges to the Status entity.
func (_c *DeploymentCreate) AddStatuses(v ...*Status) *DeploymentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStatusIDs(ids...)
}

// Mutation returns the DeploymentMutation object of the builder.
func (_c *DeploymentCreate) Mutation() *DeploymentMutation {
	return _c.mutation
}

// Save creates the Deployment in the database.
func (_c *DeploymentCreate) Save(ctx context.Context) (*Deployment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeploymentCreate) SaveX(ctx context.Context) *Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeploymentCreate) defaults() {
	if _, ok := _c.mutation.Reported(); !ok {
		v := deployment.DefaultReported
		_c.mutation.SetReported(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeploymentCreate) check() error {
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "Deployment.site_id"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "Deployment.target"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "Deployment.app_id"`)}
	}
	if _, ok := _c.mutation.AppVersion(); !ok {
		return &ValidationError{Name: "app_version", err: errors.New(`ent: missing required field "Deployment.app_version"`)}
	}
	if _, ok := _c.mutation.Profile(); !ok {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required field "Deployment.profile"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Deployment.name"`)}
	}
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "Deployment.namespace"`)}
	}
	if _, ok := _c.mutation.Parameters(); !ok {
		return &ValidationError{Name: "parameters", err: errors.New(`ent: missing required field "Deployment.parameters"`)}
	}
	if _, ok := _c.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "Deployment.digest"`)}
	}
	if _, ok := _c.mutation.DigestVersion(); !ok {
		return &ValidationError{Name: "digest_version", err: errors.New(`ent: missing required field "Deployment.digest_version"`)}
	}
	if _, ok := _c.mutation.Deleted(); !ok {
		return &ValidationError{Name: "deleted", err: errors.New(`ent: missing required field "Deployment.deleted"`)}
	}
	if _, ok := _c.mutation.DeletedVersion(); !ok {
		return &ValidationError{Name: "deleted_version", err: errors.New(`ent: missing required field "Deployment.deleted_version"`)}
	}
	if _, ok := _c.mutation.Removed(); !ok {
		return &ValidationError{Name: "removed", err: errors.New(`ent: missing required field "Deployment.removed"`)}
	}
	if _, ok := _c.mutation.Reported(); !ok {
		return &ValidationError{Name: "reported", err: errors.New(`ent: missing required field "Deployment.reported"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "Deployment.site"`)}
	}
	return nil
}

func (_c *DeploymentCreate) sqlSave(ctx context.Context) (*Deployment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeploymentCreate) createSpec() (*Deployment, *sqlgraph.CreateSpec) {
	var (
		_node = &Deployment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(deployment.Table, sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(deployment.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(deployment.FieldAppID, field.TypeString, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.AppVersion(); ok {
		_spec.SetField(deployment.FieldAppVersion, field.TypeString, value)
		_node.AppVersion = value
	}
	if value, ok := _c.mutation.Profile(); ok {
		_spec.SetField(deployment.FieldProfile, field.TypeString, value)
		_node.Profile = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(deployment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(deployment.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Parameters(); ok {
		_spec.SetField(deployment.FieldParameters, field.TypeBytes, value)
		_node.Parameters = value
	}
	if value, ok := _c.mutation.Digest(); ok {
		_spec.SetField(deployment.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if value, ok := _c.mutation.DigestVersion(); ok {
		_spec.SetField(deployment.FieldDigestVersion, field.TypeUint64, value)
		_node.DigestVersion = value
	}
	if value, ok := _c.mutation.Deleted(); ok {
		_spec.SetField(deployment.FieldDeleted, field.TypeBool, value)
		_node.Deleted = value
	}
	if value, ok := _c.mutation.DeletedVersion(); ok {
		_spec.SetField(deployment.FieldDeletedVersion, field.TypeUint64, value)
		_node.DeletedVersion = value
	}
	if value, ok := _c.mutation.Removed(); ok {
		_spec.SetField(deployment.FieldRemoved, field.TypeBool, value)
		_node.Removed = value
	}
	if value, ok := _c.mutation.Reported(); ok {
		_spec.SetField(deployment.FieldReported, field.TypeBool, value)
		_node.Reported = value
	}
	if value, ok := _c.mutation.CurrentStatus(); ok {
		_spec.SetField(deployment.FieldCurrentStatus, field.TypeBytes, value)
		_node.CurrentStatus = &value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deployment.SiteTable,
			Columns: []string{deployment.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StatusesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deployment.StatusesTable,
			Columns: []string{deployment.StatusesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deployment.Create().
//		SetSiteID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentUpsert) {
//			SetSiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeploymentCreate) OnConflict(opts ...sql.ConflictOption) *DeploymentUpsertOne {
	_c.conflict = opts
	return &DeploymentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeploymentCreate) OnConflictColumns(columns ...string) *DeploymentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeploymentUpsertOne{
		create: _c,
	}
}

type (
	// DeploymentUpsertOne is the builder for "upsert"-ing
	//  one Deployment node.
	DeploymentUpsertOne struct {
		create *DeploymentCreate
	}

	// DeploymentUpsert is the "OnConflict" setter.
	DeploymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTarget sets the "target" field.
func (u *DeploymentUpsert) SetTarget(v string) *DeploymentUpsert {
	u.Set(deployment.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateTarget() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldTarget)
	return u
}

// SetAppID sets the "app_id" field.
func (u *DeploymentUpsert) SetAppID(v string) *DeploymentUpsert {
	u.Set(deployment.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateAppID() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldAppID)
	return u
}

// SetAppVersion sets the "app_version" field.
func (u *DeploymentUpsert) SetAppVersion(v string) *DeploymentUpsert {
	u.Set(deployment.FieldAppVersion, v)
	return u
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateAppVersion() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldAppVersion)
	return u
}

// SetProfile sets the "profile" field.
func (u *DeploymentUpsert) SetProfile(v string) *DeploymentUpsert {
	u.Set(deployment.FieldProfile, v)
	return u
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateProfile() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldProfile)
	return u
}

// SetName sets the "name" field.
func (u *DeploymentUpsert) SetName(v string) *DeploymentUpsert {
	u.Set(deployment.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateName() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldName)
	return u
}

// SetNamespace sets the "namespace" field.
func (u *DeploymentUpsert) SetNamespace(v string) *DeploymentUpsert {
	u.Set(deployment.FieldNamespace, v)
	return u
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateNamespace() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldNamespace)
	return u
}

// SetParameters sets the "parameters" field.
func (u *DeploymentUpsert) SetParameters(v []byte) *DeploymentUpsert {
	u.Set(deployment.FieldParameters, v)
	return u
}

// UpdateParameters sets the "parameters" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateParameters() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldParameters)
	return u
}

// SetDigest sets the "digest" field.
func (u *DeploymentUpsert) SetDigest(v string) *DeploymentUpsert {
	u.Set(deployment.FieldDigest, v)
	return u
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateDigest() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldDigest)
	return u
}

// SetDigestVersion sets the "digest_version" field.
func (u *DeploymentUpsert) SetDigestVersion(v uint64) *DeploymentUpsert {
	u.Set(deployment.FieldDigestVersion, v)
	return u
}

// UpdateDigestVersion sets the "digest_version" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateDigestVersion() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldDigestVersion)
	return u
}

// AddDigestVersion adds v to the "digest_version" field.
func (u *DeploymentUpsert) AddDigestVersion(v uint64) *DeploymentUpsert {
	u.Add(deployment.FieldDigestVersion, v)
	return u
}

// SetDeleted sets the "deleted" field.
func (u *DeploymentUpsert) SetDeleted(v bool) *DeploymentUpsert {
	u.Set(deployment.FieldDeleted, v)
	return u
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateDeleted() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldDeleted)
	return u
}

// SetDeletedVersion sets the "deleted_version" field.
func (u *DeploymentUpsert) SetDeletedVersion(v uint64) *DeploymentUpsert {
	u.Set(deployment.FieldDeletedVersion, v)
	return u
}

// UpdateDeletedVersion sets the "deleted_version" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateDeletedVersion() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldDeletedVersion)
	return u
}

// AddDeletedVersion adds v to the "deleted_version" field.
func (u *DeploymentUpsert) AddDeletedVersion(v uint64) *DeploymentUpsert {
	u.Add(deployment.FieldDeletedVersion, v)
	return u
}

// SetRemoved sets the "removed" field.
func (u *DeploymentUpsert) SetRemoved(v bool) *DeploymentUpsert {
	u.Set(deployment.FieldRemoved, v)
	return u
}

// UpdateRemoved sets the "removed" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateRemoved() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldRemoved)
	return u
}

// SetReported sets the "reported" field.
func (u *DeploymentUpsert) SetReported(v bool) *DeploymentUpsert {
	u.Set(deployment.FieldReported, v)
	return u
}

// UpdateReported sets the "reported" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateReported() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldReported)
	return u
}

// SetCurrentStatus sets the "current_status" field.
func (u *DeploymentUpsert) SetCurrentStatus(v []byte) *DeploymentUpsert {
	u.Set(deployment.FieldCurrentStatus, v)
	return u
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *DeploymentUpsert) UpdateCurrentStatus() *DeploymentUpsert {
	u.SetExcluded(deployment.FieldCurrentStatus)
	return u
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *DeploymentUpsert) ClearCurrentStatus() *DeploymentUpsert {
	u.SetNull(deployment.FieldCurrentStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentUpsertOne) UpdateNewValues() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(deployment.FieldID)
		}
		if _, exists := u.create.mutation.SiteID(); exists {
			s.SetIgnore(deployment.FieldSiteID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeploymentUpsertOne) Ignore() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentUpsertOne) DoNothing() *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentCreate.OnConflict
// documentation for more info.
func (u *DeploymentUpsertOne) Update(set func(*DeploymentUpsert)) *DeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTarget sets the "target" field.
func (u *DeploymentUpsertOne) SetTarget(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateTarget() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateTarget()
	})
}

// SetAppID sets the "app_id" field.
func (u *DeploymentUpsertOne) SetAppID(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateAppID() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAppID()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *DeploymentUpsertOne) SetAppVersion(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateAppVersion() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAppVersion()
	})
}

// SetProfile sets the "profile" field.
func (u *DeploymentUpsertOne) SetProfile(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateProfile() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateProfile()
	})
}

// SetName sets the "name" field.
func (u *DeploymentUpsertOne) SetName(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateName() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateName()
	})
}

// SetNamespace sets the "namespace" field.
func (u *DeploymentUpsertOne) SetNamespace(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateNamespace() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateNamespace()
	})
}

// SetParameters sets the "parameters" field.
func (u *DeploymentUpsertOne) SetParameters(v []byte) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetParameters(v)
	})
}

// UpdateParameters sets the "parameters" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateParameters() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateParameters()
	})
}

// SetDigest sets the "digest" field.
func (u *DeploymentUpsertOne) SetDigest(v string) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDigest(v)
	})
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateDigest() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDigest()
	})
}

// SetDigestVersion sets the "digest_version" field.
func (u *DeploymentUpsertOne) SetDigestVersion(v uint64) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDigestVersion(v)
	})
}

// AddDigestVersion adds v to the "digest_version" field.
func (u *DeploymentUpsertOne) AddDigestVersion(v uint64) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.AddDigestVersion(v)
	})
}

// UpdateDigestVersion sets the "digest_version" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateDigestVersion() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDigestVersion()
	})
}

// SetDeleted sets the "deleted" field.
func (u *DeploymentUpsertOne) SetDeleted(v bool) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateDeleted() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDeleted()
	})
}

// SetDeletedVersion sets the "deleted_version" field.
func (u *DeploymentUpsertOne) SetDeletedVersion(v uint64) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDeletedVersion(v)
	})
}

// AddDeletedVersion adds v to the "deleted_version" field.
func (u *DeploymentUpsertOne) AddDeletedVersion(v uint64) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.AddDeletedVersion(v)
	})
}

// UpdateDeletedVersion sets the "deleted_version" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateDeletedVersion() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDeletedVersion()
	})
}

// SetRemoved sets the "removed" field.
func (u *DeploymentUpsertOne) SetRemoved(v bool) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetRemoved(v)
	})
}

// UpdateRemoved sets the "removed" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateRemoved() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateRemoved()
	})
}

// SetReported sets the "reported" field.
func (u *DeploymentUpsertOne) SetReported(v bool) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetReported(v)
	})
}

// UpdateReported sets the "reported" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateReported() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateReported()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *DeploymentUpsertOne) SetCurrentStatus(v []byte) *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *DeploymentUpsertOne) UpdateCurrentStatus() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateCurrentStatus()
	})
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *DeploymentUpsertOne) ClearCurrentStatus() *DeploymentUpsertOne {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearCurrentStatus()
	})
}

// Exec executes the query.
func (u *DeploymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeploymentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DeploymentUpsertOne.ID is not supported by MySQL driver. Use DeploymentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeploymentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeploymentCreateBulk is the builder for creating many Deployment entities in bulk.
type DeploymentCreateBulk struct {
	config
	err      error
	builders []*DeploymentCreate
	conflict []sql.ConflictOption
}

// Save creates the Deployment entities in the database.
func (_c *DeploymentCreateBulk) Save(ctx context.Context) ([]*Deployment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Deployment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeploymentCreateBulk) SaveX(ctx context.Context) []*Deployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Deployment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeploymentUpsert) {
//			SetSiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *DeploymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeploymentUpsertBulk {
	_c.conflict = opts
	return &DeploymentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeploymentCreateBulk) OnConflictColumns(columns ...string) *DeploymentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeploymentUpsertBulk{
		create: _c,
	}
}

// DeploymentUpsertBulk is the builder for "upsert"-ing
// a bulk of Deployment nodes.
type DeploymentUpsertBulk struct {
	create *DeploymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(deployment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DeploymentUpsertBulk) UpdateNewValues() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(deployment.FieldID)
			}
			if _, exists := b.mutation.SiteID(); exists {
				s.SetIgnore(deployment.FieldSiteID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Deployment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeploymentUpsertBulk) Ignore() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeploymentUpsertBulk) DoNothing() *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeploymentCreateBulk.OnConflict
// documentation for more info.
func (u *DeploymentUpsertBulk) Update(set func(*DeploymentUpsert)) *DeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTarget sets the "target" field.
func (u *DeploymentUpsertBulk) SetTarget(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateTarget() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateTarget()
	})
}

// SetAppID sets the "app_id" field.
func (u *DeploymentUpsertBulk) SetAppID(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateAppID() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAppID()
	})
}

// SetAppVersion sets the "app_version" field.
func (u *DeploymentUpsertBulk) SetAppVersion(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetAppVersion(v)
	})
}

// UpdateAppVersion sets the "app_version" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateAppVersion() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateAppVersion()
	})
}

// SetProfile sets the "profile" field.
func (u *DeploymentUpsertBulk) SetProfile(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetProfile(v)
	})
}

// UpdateProfile sets the "profile" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateProfile() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateProfile()
	})
}

// SetName sets the "name" field.
func (u *DeploymentUpsertBulk) SetName(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateName() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateName()
	})
}

// SetNamespace sets the "namespace" field.
func (u *DeploymentUpsertBulk) SetNamespace(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateNamespace() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateNamespace()
	})
}

// SetParameters sets the "parameters" field.
func (u *DeploymentUpsertBulk) SetParameters(v []byte) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetParameters(v)
	})
}

// UpdateParameters sets the "parameters" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateParameters() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateParameters()
	})
}

// SetDigest sets the "digest" field.
func (u *DeploymentUpsertBulk) SetDigest(v string) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDigest(v)
	})
}

// UpdateDigest sets the "digest" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateDigest() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDigest()
	})
}

// SetDigestVersion sets the "digest_version" field.
func (u *DeploymentUpsertBulk) SetDigestVersion(v uint64) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDigestVersion(v)
	})
}

// AddDigestVersion adds v to the "digest_version" field.
func (u *DeploymentUpsertBulk) AddDigestVersion(v uint64) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.AddDigestVersion(v)
	})
}

// UpdateDigestVersion sets the "digest_version" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateDigestVersion() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDigestVersion()
	})
}

// SetDeleted sets the "deleted" field.
func (u *DeploymentUpsertBulk) SetDeleted(v bool) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDeleted(v)
	})
}

// UpdateDeleted sets the "deleted" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateDeleted() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDeleted()
	})
}

// SetDeletedVersion sets the "deleted_version" field.
func (u *DeploymentUpsertBulk) SetDeletedVersion(v uint64) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetDeletedVersion(v)
	})
}

// AddDeletedVersion adds v to the "deleted_version" field.
func (u *DeploymentUpsertBulk) AddDeletedVersion(v uint64) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.AddDeletedVersion(v)
	})
}

// UpdateDeletedVersion sets the "deleted_version" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateDeletedVersion() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateDeletedVersion()
	})
}

// SetRemoved sets the "removed" field.
func (u *DeploymentUpsertBulk) SetRemoved(v bool) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetRemoved(v)
	})
}

// UpdateRemoved sets the "removed" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateRemoved() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateRemoved()
	})
}

// SetReported sets the "reported" field.
func (u *DeploymentUpsertBulk) SetReported(v bool) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetReported(v)
	})
}

// UpdateReported sets the "reported" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateReported() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateReported()
	})
}

// SetCurrentStatus sets the "current_status" field.
func (u *DeploymentUpsertBulk) SetCurrentStatus(v []byte) *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.SetCurrentStatus(v)
	})
}

// UpdateCurrentStatus sets the "current_status" field to the value that was provided on create.
func (u *DeploymentUpsertBulk) UpdateCurrentStatus() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.UpdateCurrentStatus()
	})
}

// ClearCurrentStatus clears the value of the "current_status" field.
func (u *DeploymentUpsertBulk) ClearCurrentStatus() *DeploymentUpsertBulk {
	return u.Update(func(s *DeploymentUpsert) {
		s.ClearCurrentStatus()
	})
}

// Exec executes the query.
func (u *DeploymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeploymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeploymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeploymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
