// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/publication"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
	"github.com/google/uuid"
)

// PublicationCreate is the builder for creating a Publication entity.
type PublicationCreate struct {
	config
	mutation *PublicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSiteID sets the "site_id" field.
func (_c *PublicationCreate) SetSiteID(v string) *PublicationCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetBundle sets the "bundle" field.
func (_c *PublicationCreate) SetBundle(v bool) *PublicationCreate {
	_c.mutation.SetBundle(v)
	return _c
}

// SetDeploymentID sets the "deployment_id" field.
func (_c *PublicationCreate) SetDeploymentID(v uuid.UUID) *PublicationCreate {
	_c.mutation.SetDeploymentID(v)
	return _c
}

// SetDigest sets the "digest" field.
func (_c *PublicationCreate) SetDigest(v string) *PublicationCreate {
	_c.mutation.SetDigest(v)
	return _c
}

// SetSite sets the "site" edge to the Site entity.
func (_c *PublicationCreate) SetSite(v *Site) *PublicationCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the PublicationMutation object of the builder.
func (_c *PublicationCreate) Mutation() *PublicationMutation {
	return _c.mutation
}

// Save creates the Publication in the database.
func (_c *PublicationCreate) Save(ctx context.Context) (*Publication, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PublicationCreate) SaveX(ctx context.Context) *Publication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PublicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PublicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PublicationCreate) check() error {
	if _, ok := _c.mutation.SiteID(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "Publication.site_id"`)}
	}
	if _, ok := _c.mutation.Bundle(); !ok {
		return &ValidationError{Name: "bundle", err: errors.New(`ent: missing required field "Publication.bundle"`)}
	}
	if _, ok := _c.mutation.DeploymentID(); !ok {
		return &ValidationError{Name: "deployment_id", err: errors.New(`ent: missing required field "Publication.deployment_id"`)}
	}
	if _, ok := _c.mutation.Digest(); !ok {
		return &ValidationError{Name: "digest", err: errors.New(`ent: missing required field "Publication.digest"`)}
	}
	if len(_c.mutation.SiteIDs()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "Publication.site"`)}
	}
	return nil
}

func (_c *PublicationCreate) sqlSave(ctx context.Context) (*Publication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PublicationCreate) createSpec() (*Publication, *sqlgraph.CreateSpec) {
	var (
		_node = &Publication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(publication.Table, sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Bundle(); ok {
		_spec.SetField(publication.FieldBundle, field.TypeBool, value)
		_node.Bundle = value
	}
	if value, ok := _c.mutation.DeploymentID(); ok {
		_spec.SetField(publication.FieldDeploymentID, field.TypeUUID, value)
		_node.DeploymentID = value
	}
	if value, ok := _c.mutation.Digest(); ok {
		_spec.SetField(publication.FieldDigest, field.TypeString, value)
		_node.Digest = value
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   publication.SiteTable,
			Columns: []string{publication.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Publication.Create().
//		SetSiteID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PublicationUpsert) {
//			SetSiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *PublicationCreate) OnConflict(opts ...sql.ConflictOption) *PublicationUpsertOne {
	_c.conflict = opts
	return &PublicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Publication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PublicationCreate) OnConflictColumns(columns ...string) *PublicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PublicationUpsertOne{
		create: _c,
	}
}

type (
	// PublicationUpsertOne is the builder for "upsert"-ing
	//  one Publication node.
	PublicationUpsertOne struct {
		create *PublicationCreate
	}

	// PublicationUpsert is the "OnConflict" setter.
	PublicationUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Publication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PublicationUpsertOne) UpdateNewValues() *PublicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.SiteID(); exists {
			s.SetIgnore(publication.FieldSiteID)
		}
		if _, exists := u.create.mutation.Bundle(); exists {
			s.SetIgnore(publication.FieldBundle)
		}
		if _, exists := u.create.mutation.DeploymentID(); exists {
			s.SetIgnore(publication.FieldDeploymentID)
		}
		if _, exists := u.create.mutation.Digest(); exists {
			s.SetIgnore(publication.FieldDigest)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Publication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PublicationUpsertOne) Ignore() *PublicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PublicationUpsertOne) DoNothing() *PublicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PublicationCreate.OnConflict
// documentation for more info.
func (u *PublicationUpsertOne) Update(set func(*PublicationUpsert)) *PublicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PublicationUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *PublicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PublicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PublicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PublicationUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PublicationUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PublicationCreateBulk is the builder for creating many Publication entities in bulk.
type PublicationCreateBulk struct {
	config
	err      error
	builders []*PublicationCreate
	conflict []sql.ConflictOption
}

// Save creates the Publication entities in the database.
func (_c *PublicationCreateBulk) Save(ctx context.Context) ([]*Publication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Publication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PublicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PublicationCreateBulk) SaveX(ctx context.Context) []*Publication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PublicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PublicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Publication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PublicationUpsert) {
//			SetSiteID(v+v).
//		}).
//		Exec(ctx)
func (_c *PublicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *PublicationUpsertBulk {
	_c.conflict = opts
	return &PublicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Publication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PublicationCreateBulk) OnConflictColumns(columns ...string) *PublicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PublicationUpsertBulk{
		create: _c,
	}
}

// PublicationUpsertBulk is the builder for "upsert"-ing
// a bulk of Publication nodes.
type PublicationUpsertBulk struct {
	create *PublicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Publication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PublicationUpsertBulk) UpdateNewValues() *PublicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.SiteID(); exists {
				s.SetIgnore(publication.FieldSiteID)
			}
			if _, exists := b.mutation.Bundle(); exists {
				s.SetIgnore(publication.FieldBundle)
			}
			if _, exists := b.mutation.DeploymentID(); exists {
				s.SetIgnore(publication.FieldDeploymentID)
			}
			if _, exists := b.mutation.Digest(); exists {
				s.SetIgnore(publication.FieldDigest)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Publication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PublicationUpsertBulk) Ignore() *PublicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PublicationUpsertBulk) DoNothing() *PublicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PublicationCreateBulk.OnConflict
// documentation for more info.
func (u *PublicationUpsertBulk) Update(set func(*PublicationUpsert)) *PublicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PublicationUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *PublicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PublicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PublicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PublicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
