// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/schema"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deploymentFields := schema.Deployment{}.Fields()
	_ = deploymentFields
	// deploymentDescReported is the schema descriptor for reported field.
	deploymentDescReported := deploymentFields[14].Descriptor()
	// deployment.DefaultReported holds the default value on creation for the reported field.
	deployment.DefaultReported = deploymentDescReported.Default.(bool)
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescRetired is the schema descriptor for retired field.
	siteDescRetired := siteFields[1].Descriptor()
	// site.DefaultRetired holds the default value on creation for the retired field.
	site.DefaultRetired = siteDescRetired.Default.(bool)
	// siteDescManifestVersion is the schema descriptor for manifest_version field.
	siteDescManifestVersion := siteFields[2].Descriptor()
	// site.DefaultManifestVersion holds the default value on creation for the manifest_version field.
	site.DefaultManifestVersion = siteDescManifestVersion.Default.(uint64)
	// siteDescManifestEtag is the schema descriptor for manifest_etag field.
	siteDescManifestEtag := siteFields[4].Descriptor()
	// site.DefaultManifestEtag holds the default value on creation for the manifest_etag field.
	site.DefaultManifestEtag = siteDescManifestEtag.Default.(string)
	// siteDescManifestBundle is the schema descriptor for manifest_bundle field.
	siteDescManifestBundle := siteFields[5].Descriptor()
	// site.DefaultManifestBundle holds the default value on creation for the manifest_bundle field.
	site.DefaultManifestBundle = siteDescManifestBundle.Default.(string)
}
