// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
)

// Site is the model entity for the Site schema.
type Site struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Retired holds the value of the "retired" field.
	Retired bool `json:"retired,omitempty"`
	// ManifestVersion holds the value of the "manifest_version" field.
	ManifestVersion uint64 `json:"manifest_version,omitempty"`
	// ManifestBody holds the value of the "manifest_body" field.
	ManifestBody []byte `json:"manifest_body,omitempty"`
	// ManifestEtag holds the value of the "manifest_etag" field.
	ManifestEtag string `json:"manifest_etag,omitempty"`
	// ManifestBundle holds the value of the "manifest_bundle" field.
	ManifestBundle string `json:"manifest_bundle,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash *[]byte `json:"token_hash,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SiteQuery when eager-loading is set.
	Edges        SiteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SiteEdges holds the relations/edges for other nodes in the graph.
type SiteEdges struct {
	// Devices holds the value of the devices edge.
	Devices []*Device `json:"devices,omitempty"`
	// Deployments holds the value of the deployments edge.
	Deployments []*Deployment `json:"deployments,omitempty"`
	// Publications holds the value of the publications edge.
	Publications []*Publication `json:"publications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DevicesOrErr returns the Devices value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) DevicesOrErr() ([]*Device, error) {
	if e.loadedTypes[0] {
		return e.Devices, nil
	}
	return nil, &NotLoadedError{edge: "devices"}
}

// DeploymentsOrErr returns the Deployments value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) DeploymentsOrErr() ([]*Deployment, error) {
	if e.loadedTypes[1] {
		return e.Deployments, nil
	}
	return nil, &NotLoadedError{edge: "deployments"}
}

// PublicationsOrErr returns the Publications value or an error if the edge
// was not loaded in eager-loading.
func (e SiteEdges) PublicationsOrErr() ([]*Publication, error) {
	if e.loadedTypes[2] {
		return e.Publications, nil
	}
	return nil, &NotLoadedError{edge: "publications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Site) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case site.FieldManifestBody, site.FieldTokenHash:
			values[i] = new([]byte)
		case site.FieldRetired:
			values[i] = new(sql.NullBool)
		case site.FieldManifestVersion:
			values[i] = new(sql.NullInt64)
		case site.FieldID, site.FieldManifestEtag, site.FieldManifestBundle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Site fields.
func (_m *Site) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case site.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case site.FieldRetired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field retired", values[i])
			} else if value.Valid {
				_m.Retired = value.Bool
			}
		case site.FieldManifestVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_version", values[i])
			} else if value.Valid {
				_m.ManifestVersion = uint64(value.Int64)
			}
		case site.FieldManifestBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_body", values[i])
			} else if value != nil {
				_m.ManifestBody = *value
			}
		case site.FieldManifestEtag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_etag", values[i])
			} else if value.Valid {
				_m.ManifestEtag = value.String
			}
		case site.FieldManifestBundle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manifest_bundle", values[i])
			} else if value.Valid {
				_m.ManifestBundle = value.String
			}
		case site.FieldTokenHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value != nil {
				_m.TokenHash = value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Site.
// This includes values selected through modifiers, order, etc.
func (_m *Site) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevices queries the "devices" edge of the Site entity.
func (_m *Site) QueryDevices() *DeviceQuery {
	return NewSiteClient(_m.config).QueryDevices(_m)
}

// QueryDeployments queries the "deployments" edge of the Site entity.
func (_m *Site) QueryDeployments() *DeploymentQuery {
	return NewSiteClient(_m.config).QueryDeployments(_m)
}

// QueryPublications queries the "publications" edge of the Site entity.
func (_m *Site) QueryPublications() *PublicationQuery {
	return NewSiteClient(_m.config).QueryPublications(_m)
}

// Update returns a builder for updating this Site.
// Note that you need to call Site.Unwrap() before calling this method if this Site
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Site) Update() *SiteUpdateOne {
	return NewSiteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Site entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Site) Unwrap() *Site {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Site is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Site) String() string {
	var builder strings.Builder
	builder.WriteString("Site(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("retired=")
	builder.WriteString(fmt.Sprintf("%v", _m.Retired))
	builder.WriteString(", ")
	builder.WriteString("manifest_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManifestVersion))
	builder.WriteString(", ")
	builder.WriteString("manifest_body=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManifestBody))
	builder.WriteString(", ")
	builder.WriteString("manifest_etag=")
	builder.WriteString(_m.ManifestEtag)
	builder.WriteString(", ")
	builder.WriteString("manifest_bundle=")
	builder.WriteString(_m.ManifestBundle)
	builder.WriteString(", ")
	if v := _m.TokenHash; v != nil {
		builder.WriteString("token_hash=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sites is a parsable slice of Site.
type Sites []*Site
