// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/device"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/publication"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
	"github.com/google/uuid"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRetired sets the "retired" field.
func (_u *SiteUpdate) SetRetired(v bool) *SiteUpdate {
	_u.mutation.SetRetired(v)
	return _u
}

// SetNillableRetired sets the "retired" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableRetired(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetRetired(*v)
	}
	return _u
}

// SetManifestVersion sets the "manifest_version" field.
func (_u *SiteUpdate) SetManifestVersion(v uint64) *SiteUpdate {
	_u.mutation.ResetManifestVersion()
	_u.mutation.SetManifestVersion(v)
	return _u
}

// SetNillableManifestVersion sets the "manifest_version" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableManifestVersion(v *uint64) *SiteUpdate {
	if v != nil {
		_u.SetManifestVersion(*v)
	}
	return _u
}

// AddManifestVersion adds value to the "manifest_version" field.
func (_u *SiteUpdate) AddManifestVersion(v int64) *SiteUpdate {
	_u.mutation.AddManifestVersion(v)
	return _u
}

// SetManifestBody sets the "manifest_body" field.
func (_u *SiteUpdate) SetManifestBody(v []byte) *SiteUpdate {
	_u.mutation.SetManifestBody(v)
	return _u
}

// ClearManifestBody clears the value of the "manifest_body" field.
func (_u *SiteUpdate) ClearManifestBody() *SiteUpdate {
	_u.mutation.ClearManifestBody()
	return _u
}

// SetManifestEtag sets the "manifest_etag" field.
func (_u *SiteUpdate) SetManifestEtag(v string) *SiteUpdate {
	_u.mutation.SetManifestEtag(v)
	return _u
}

// SetNillableManifestEtag sets the "manifest_etag" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableManifestEtag(v *string) *SiteUpdate {
	if v != nil {
		_u.SetManifestEtag(*v)
	}
	return _u
}

// SetManifestBundle sets the "manifest_bundle" field.
func (_u *SiteUpdate) SetManifestBundle(v string) *SiteUpdate {
	_u.mutation.SetManifestBundle(v)
	return _u
}

// SetNillableManifestBundle sets the "manifest_bundle" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableManifestBundle(v *string) *SiteUpdate {
	if v != nil {
		_u.SetManifestBundle(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SiteUpdate) SetTokenHash(v []byte) *SiteUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *SiteUpdate) ClearTokenHash() *SiteUpdate {
	_u.mutation.ClearTokenHash()
	return _u
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *SiteUpdate) AddDeviceIDs(ids ...int) *SiteUpdate {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *SiteUpdate) AddDevices(v ...*Device) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// AddDeploymentIDs adds the "deployments" edge to the Deployment entity by IDs.
func (_u *SiteUpdate) AddDeploymentIDs(ids ...uuid.UUID) *SiteUpdate {
	_u.mutation.AddDeploymentIDs(ids...)
	return _u
}

// AddDeployments adds the "deployments" edges to the Deployment entity.
func (_u *SiteUpdate) AddDeployments(v ...*Deployment) *SiteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeploymentIDs(ids...)
}

// AddPublicationIDs adds the "publications" edge to the Publication entity by IDs.
func (_u *SiteUpdate) AddPublicationIDs(ids ...int) *SiteUpdate {
	_u.mutation.AddPublicationIDs(ids...)
	return _u
}

// AddPublications adds the "publications" edges to the Publication entity.
func (_u *SiteUpdate) AddPublications(v ...*Publication) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublicationIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *SiteUpdate) ClearDevices() *SiteUpdate {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *SiteUpdate) RemoveDeviceIDs(ids ...int) *SiteUpdate {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *SiteUpdate) RemoveDevices(v ...*Device) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// ClearDeployments clears all "deployments" edges to the Deployment entity.
func (_u *SiteUpdate) ClearDeployments() *SiteUpdate {
	_u.mutation.ClearDeployments()
	return _u
}

// RemoveDeploymentIDs removes the "deployments" edge to Deployment entities by IDs.
func (_u *SiteUpdate) RemoveDeploymentIDs(ids ...uuid.UUID) *SiteUpdate {
	_u.mutation.RemoveDeploymentIDs(ids...)
	return _u
}

// RemoveDeployments removes "deployments" edges to Deployment entities.
func (_u *SiteUpdate) RemoveDeployments(v ...*Deployment) *SiteUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeploymentIDs(ids...)
}

// ClearPublications clears all "publications" edges to the Publication entity.
func (_u *SiteUpdate) ClearPublications() *SiteUpdate {
	_u.mutation.ClearPublications()
	return _u
}

// RemovePublicationIDs removes the "publications" edge to Publication entities by IDs.
func (_u *SiteUpdate) RemovePublicationIDs(ids ...int) *SiteUpdate {
	_u.mutation.RemovePublicationIDs(ids...)
	return _u
}

// RemovePublications removes "publications" edges to Publication entities.
func (_u *SiteUpdate) RemovePublications(v ...*Publication) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublicationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Retired(); ok {
		_spec.SetField(site.FieldRetired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManifestVersion(); ok {
		_spec.SetField(site.FieldManifestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedManifestVersion(); ok {
		_spec.AddField(site.FieldManifestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ManifestBody(); ok {
		_spec.SetField(site.FieldManifestBody, field.TypeBytes, value)
	}
	if _u.mutation.ManifestBodyCleared() {
		_spec.ClearField(site.FieldManifestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ManifestEtag(); ok {
		_spec.SetField(site.FieldManifestEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestBundle(); ok {
		_spec.SetField(site.FieldManifestBundle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(site.FieldTokenHash, field.TypeBytes, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(site.FieldTokenHash, field.TypeBytes)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeploymentsIDs(); len(nodes) > 0 && !_u.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublicationsIDs(); len(nodes) > 0 && !_u.mutation.PublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMutation
}

// SetRetired sets the "retired" field.
func (_u *SiteUpdateOne) SetRetired(v bool) *SiteUpdateOne {
	_u.mutation.SetRetired(v)
	return _u
}

// SetNillableRetired sets the "retired" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableRetired(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetRetired(*v)
	}
	return _u
}

// SetManifestVersion sets the "manifest_version" field.
func (_u *SiteUpdateOne) SetManifestVersion(v uint64) *SiteUpdateOne {
	_u.mutation.ResetManifestVersion()
	_u.mutation.SetManifestVersion(v)
	return _u
}

// SetNillableManifestVersion sets the "manifest_version" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableManifestVersion(v *uint64) *SiteUpdateOne {
	if v != nil {
		_u.SetManifestVersion(*v)
	}
	return _u
}

// AddManifestVersion adds value to the "manifest_version" field.
func (_u *SiteUpdateOne) AddManifestVersion(v int64) *SiteUpdateOne {
	_u.mutation.AddManifestVersion(v)
	return _u
}

// SetManifestBody sets the "manifest_body" field.
func (_u *SiteUpdateOne) SetManifestBody(v []byte) *SiteUpdateOne {
	_u.mutation.SetManifestBody(v)
	return _u
}

// ClearManifestBody clears the value of the "manifest_body" field.
func (_u *SiteUpdateOne) ClearManifestBody() *SiteUpdateOne {
	_u.mutation.ClearManifestBody()
	return _u
}

// SetManifestEtag sets the "manifest_etag" field.
func (_u *SiteUpdateOne) SetManifestEtag(v string) *SiteUpdateOne {
	_u.mutation.SetManifestEtag(v)
	return _u
}

// SetNillableManifestEtag sets the "manifest_etag" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableManifestEtag(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetManifestEtag(*v)
	}
	return _u
}

// SetManifestBundle sets the "manifest_bundle" field.
func (_u *SiteUpdateOne) SetManifestBundle(v string) *SiteUpdateOne {
	_u.mutation.SetManifestBundle(v)
	return _u
}

// SetNillableManifestBundle sets the "manifest_bundle" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableManifestBundle(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetManifestBundle(*v)
	}
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SiteUpdateOne) SetTokenHash(v []byte) *SiteUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (_u *SiteUpdateOne) ClearTokenHash() *SiteUpdateOne {
	_u.mutation.ClearTokenHash()
	return _u
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_u *SiteUpdateOne) AddDeviceIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.AddDeviceIDs(ids...)
	return _u
}

// AddDevices adds the "devices" edges to the Device entity.
func (_u *SiteUpdateOne) AddDevices(v ...*Device) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeviceIDs(ids...)
}

// AddDeploymentIDs adds the "deployments" edge to the Deployment entity by IDs.
func (_u *SiteUpdateOne) AddDeploymentIDs(ids ...uuid.UUID) *SiteUpdateOne {
	_u.mutation.AddDeploymentIDs(ids...)
	return _u
}

// AddDeployments adds the "deployments" edges to the Deployment entity.
func (_u *SiteUpdateOne) AddDeployments(v ...*Deployment) *SiteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeploymentIDs(ids...)
}

// AddPublicationIDs adds the "publications" edge to the Publication entity by IDs.
func (_u *SiteUpdateOne) AddPublicationIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.AddPublicationIDs(ids...)
	return _u
}

// AddPublications adds the "publications" edges to the Publication entity.
func (_u *SiteUpdateOne) AddPublications(v ...*Publication) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublicationIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearDevices clears all "devices" edges to the Device entity.
func (_u *SiteUpdateOne) ClearDevices() *SiteUpdateOne {
	_u.mutation.ClearDevices()
	return _u
}

// RemoveDeviceIDs removes the "devices" edge to Device entities by IDs.
func (_u *SiteUpdateOne) RemoveDeviceIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.RemoveDeviceIDs(ids...)
	return _u
}

// RemoveDevices removes "devices" edges to Device entities.
func (_u *SiteUpdateOne) RemoveDevices(v ...*Device) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeviceIDs(ids...)
}

// ClearDeployments clears all "deployments" edges to the Deployment entity.
func (_u *SiteUpdateOne) ClearDeployments() *SiteUpdateOne {
	_u.mutation.ClearDeployments()
	return _u
}

// RemoveDeploymentIDs removes the "deployments" edge to Deployment entities by IDs.
func (_u *SiteUpdateOne) RemoveDeploymentIDs(ids ...uuid.UUID) *SiteUpdateOne {
	_u.mutation.RemoveDeploymentIDs(ids...)
	return _u
}

// RemoveDeployments removes "deployments" edges to Deployment entities.
func (_u *SiteUpdateOne) RemoveDeployments(v ...*Deployment) *SiteUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeploymentIDs(ids...)
}

// ClearPublications clears all "publications" edges to the Publication entity.
func (_u *SiteUpdateOne) ClearPublications() *SiteUpdateOne {
	_u.mutation.ClearPublications()
	return _u
}

// RemovePublicationIDs removes the "publications" edge to Publication entities by IDs.
func (_u *SiteUpdateOne) RemovePublicationIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.RemovePublicationIDs(ids...)
	return _u
}

// RemovePublications removes "publications" edges to Publication entities.
func (_u *SiteUpdateOne) RemovePublications(v ...*Publication) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublicationIDs(ids...)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Retired(); ok {
		_spec.SetField(site.FieldRetired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ManifestVersion(); ok {
		_spec.SetField(site.FieldManifestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedManifestVersion(); ok {
		_spec.AddField(site.FieldManifestVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ManifestBody(); ok {
		_spec.SetField(site.FieldManifestBody, field.TypeBytes, value)
	}
	if _u.mutation.ManifestBodyCleared() {
		_spec.ClearField(site.FieldManifestBody, field.TypeBytes)
	}
	if value, ok := _u.mutation.ManifestEtag(); ok {
		_spec.SetField(site.FieldManifestEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestBundle(); ok {
		_spec.SetField(site.FieldManifestBundle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(site.FieldTokenHash, field.TypeBytes, value)
	}
	if _u.mutation.TokenHashCleared() {
		_spec.ClearField(site.FieldTokenHash, field.TypeBytes)
	}
	if _u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDevicesIDs(); len(nodes) > 0 && !_u.mutation.DevicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeploymentsIDs(); len(nodes) > 0 && !_u.mutation.DeploymentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublicationsIDs(); len(nodes) > 0 && !_u.mutation.PublicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
