// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/deployment"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/device"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/publication"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/site"
	"github.com/google/uuid"
)

// SiteCreate is the builder for creating a Site entity.
type SiteCreate struct {
	config
	mutation *SiteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRetired sets the "retired" field.
func (_c *SiteCreate) SetRetired(v bool) *SiteCreate {
	_c.mutation.SetRetired(v)
	return _c
}

// SetNillableRetired sets the "retired" field if the given value is not nil.
func (_c *SiteCreate) SetNillableRetired(v *bool) *SiteCreate {
	if v != nil {
		_c.SetRetired(*v)
	}
	return _c
}

// SetManifestVersion sets the "manifest_version" field.
func (_c *SiteCreate) SetManifestVersion(v uint64) *SiteCreate {
	_c.mutation.SetManifestVersion(v)
	return _c
}

// SetNillableManifestVersion sets the "manifest_version" field if the given value is not nil.
func (_c *SiteCreate) SetNillableManifestVersion(v *uint64) *SiteCreate {
	if v != nil {
		_c.SetManifestVersion(*v)
	}
	return _c
}

// SetManifestBody sets the "manifest_body" field.
func (_c *SiteCreate) SetManifestBody(v []byte) *SiteCreate {
	_c.mutation.SetManifestBody(v)
	return _c
}

// SetManifestEtag sets the "manifest_etag" field.
func (_c *SiteCreate) SetManifestEtag(v string) *SiteCreate {
	_c.mutation.SetManifestEtag(v)
	return _c
}

// SetNillableManifestEtag sets the "manifest_etag" field if the given value is not nil.
func (_c *SiteCreate) SetNillableManifestEtag(v *string) *SiteCreate {
	if v != nil {
		_c.SetManifestEtag(*v)
	}
	return _c
}

// SetManifestBundle sets the "manifest_bundle" field.
func (_c *SiteCreate) SetManifestBundle(v string) *SiteCreate {
	_c.mutation.SetManifestBundle(v)
	return _c
}

// SetNillableManifestBundle sets the "manifest_bundle" field if the given value is not nil.
func (_c *SiteCreate) SetNillableManifestBundle(v *string) *SiteCreate {
	if v != nil {
		_c.SetManifestBundle(*v)
	}
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *SiteCreate) SetTokenHash(v []byte) *SiteCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SiteCreate) SetID(v string) *SiteCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddDeviceIDs adds the "devices" edge to the Device entity by IDs.
func (_c *SiteCreate) AddDeviceIDs(ids ...int) *SiteCreate {
	_c.mutation.AddDeviceIDs(ids...)
	return _c
}

// AddDevices adds the "devices" edges to the Device entity.
func (_c *SiteCreate) AddDevices(v ...*Device) *SiteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeviceIDs(ids...)
}

// AddDeploymentIDs adds the "deployments" edge to the Deployment entity by IDs.
func (_c *SiteCreate) AddDeploymentIDs(ids ...uuid.UUID) *SiteCreate {
	_c.mutation.AddDeploymentIDs(ids...)
	return _c
}

// AddDeployments adds the "deployments" edges to the Deployment entity.
func (_c *SiteCreate) AddDeployments(v ...*Deployment) *SiteCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeploymentIDs(ids...)
}

// AddPublicationIDs adds the "publications" edge to the Publication entity by IDs.
func (_c *SiteCreate) AddPublicationIDs(ids ...int) *SiteCreate {
	_c.mutation.AddPublicationIDs(ids...)
	return _c
}

// AddPublications adds the "publications" edges to the Publication entity.
func (_c *SiteCreate) AddPublications(v ...*Publication) *SiteCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPublicationIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_c *SiteCreate) Mutation() *SiteMutation {
	return _c.mutation
}

// Save creates the Site in the database.
func (_c *SiteCreate) Save(ctx context.Context) (*Site, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteCreate) SaveX(ctx context.Context) *Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SiteCreate) defaults() {
	if _, ok := _c.mutation.Retired(); !ok {
		v := site.DefaultRetired
		_c.mutation.SetRetired(v)
	}
	if _, ok := _c.mutation.ManifestVersion(); !ok {
		v := site.DefaultManifestVersion
		_c.mutation.SetManifestVersion(v)
	}
	if _, ok := _c.mutation.ManifestEtag(); !ok {
		v := site.DefaultManifestEtag
		_c.mutation.SetManifestEtag(v)
	}
	if _, ok := _c.mutation.ManifestBundle(); !ok {
		v := site.DefaultManifestBundle
		_c.mutation.SetManifestBundle(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteCreate) check() error {
	if _, ok := _c.mutation.Retired(); !ok {
		return &ValidationError{Name: "retired", err: errors.New(`ent: missing required field "Site.retired"`)}
	}
	if _, ok := _c.mutation.ManifestVersion(); !ok {
		return &ValidationError{Name: "manifest_version", err: errors.New(`ent: missing required field "Site.manifest_version"`)}
	}
	if _, ok := _c.mutation.ManifestEtag(); !ok {
		return &ValidationError{Name: "manifest_etag", err: errors.New(`ent: missing required field "Site.manifest_etag"`)}
	}
	if _, ok := _c.mutation.ManifestBundle(); !ok {
		return &ValidationError{Name: "manifest_bundle", err: errors.New(`ent: missing required field "Site.manifest_bundle"`)}
	}
	return nil
}

func (_c *SiteCreate) sqlSave(ctx context.Context) (*Site, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Site.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteCreate) createSpec() (*Site, *sqlgraph.CreateSpec) {
	var (
		_node = &Site{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(site.Table, sqlgraph.NewFieldSpec(site.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Retired(); ok {
		_spec.SetField(site.FieldRetired, field.TypeBool, value)
		_node.Retired = value
	}
	if value, ok := _c.mutation.ManifestVersion(); ok {
		_spec.SetField(site.FieldManifestVersion, field.TypeUint64, value)
		_node.ManifestVersion = value
	}
	if value, ok := _c.mutation.ManifestBody(); ok {
		_spec.SetField(site.FieldManifestBody, field.TypeBytes, value)
		_node.ManifestBody = value
	}
	if value, ok := _c.mutation.ManifestEtag(); ok {
		_spec.SetField(site.FieldManifestEtag, field.TypeString, value)
		_node.ManifestEtag = value
	}
	if value, ok := _c.mutation.ManifestBundle(); ok {
		_spec.SetField(site.FieldManifestBundle, field.TypeString, value)
		_node.ManifestBundle = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(site.FieldTokenHash, field.TypeBytes, value)
		_node.TokenHash = &value
	}
	if nodes := _c.mutation.DevicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DevicesTable,
			Columns: []string{site.DevicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeploymentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.DeploymentsTable,
			Columns: []string{site.DeploymentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deployment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PublicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   site.PublicationsTable,
			Columns: []string{site.PublicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(publication.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Site.Create().
//		SetRetired(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteUpsert) {
//			SetRetired(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteCreate) OnConflict(opts ...sql.ConflictOption) *SiteUpsertOne {
	_c.conflict = opts
	return &SiteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteCreate) OnConflictColumns(columns ...string) *SiteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteUpsertOne{
		create: _c,
	}
}

type (
	// SiteUpsertOne is the builder for "upsert"-ing
	//  one Site node.
	SiteUpsertOne struct {
		create *SiteCreate
	}

	// SiteUpsert is the "OnConflict" setter.
	SiteUpsert struct {
		*sql.UpdateSet
	}
)

// SetRetired sets the "retired" field.
func (u *SiteUpsert) SetRetired(v bool) *SiteUpsert {
	u.Set(site.FieldRetired, v)
	return u
}

// UpdateRetired sets the "retired" field to the value that was provided on create.
func (u *SiteUpsert) UpdateRetired() *SiteUpsert {
	u.SetExcluded(site.FieldRetired)
	return u
}

// SetManifestVersion sets the "manifest_version" field.
func (u *SiteUpsert) SetManifestVersion(v uint64) *SiteUpsert {
	u.Set(site.FieldManifestVersion, v)
	return u
}

// UpdateManifestVersion sets the "manifest_version" field to the value that was provided on create.
func (u *SiteUpsert) UpdateManifestVersion() *SiteUpsert {
	u.SetExcluded(site.FieldManifestVersion)
	return u
}

// AddManifestVersion adds v to the "manifest_version" field.
func (u *SiteUpsert) AddManifestVersion(v uint64) *SiteUpsert {
	u.Add(site.FieldManifestVersion, v)
	return u
}

// SetManifestBody sets the "manifest_body" field.
func (u *SiteUpsert) SetManifestBody(v []byte) *SiteUpsert {
	u.Set(site.FieldManifestBody, v)
	return u
}

// UpdateManifestBody sets the "manifest_body" field to the value that was provided on create.
func (u *SiteUpsert) UpdateManifestBody() *SiteUpsert {
	u.SetExcluded(site.FieldManifestBody)
	return u
}

// ClearManifestBody clears the value of the "manifest_body" field.
func (u *SiteUpsert) ClearManifestBody() *SiteUpsert {
	u.SetNull(site.FieldManifestBody)
	return u
}

// SetManifestEtag sets the "manifest_etag" field.
func (u *SiteUpsert) SetManifestEtag(v string) *SiteUpsert {
	u.Set(site.FieldManifestEtag, v)
	return u
}

// UpdateManifestEtag sets the "manifest_etag" field to the value that was provided on create.
func (u *SiteUpsert) UpdateManifestEtag() *SiteUpsert {
	u.SetExcluded(site.FieldManifestEtag)
	return u
}

// SetManifestBundle sets the "manifest_bundle" field.
func (u *SiteUpsert) SetManifestBundle(v string) *SiteUpsert {
	u.Set(site.FieldManifestBundle, v)
	return u
}

// UpdateManifestBundle sets the "manifest_bundle" field to the value that was provided on create.
func (u *SiteUpsert) UpdateManifestBundle() *SiteUpsert {
	u.SetExcluded(site.FieldManifestBundle)
	return u
}

// SetTokenHash sets the "token_hash" field.
func (u *SiteUpsert) SetTokenHash(v []byte) *SiteUpsert {
	u.Set(site.FieldTokenHash, v)
	return u
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SiteUpsert) UpdateTokenHash() *SiteUpsert {
	u.SetExcluded(site.FieldTokenHash)
	return u
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SiteUpsert) ClearTokenHash() *SiteUpsert {
	u.SetNull(site.FieldTokenHash)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(site.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SiteUpsertOne) UpdateNewValues() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(site.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SiteUpsertOne) Ignore() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteUpsertOne) DoNothing() *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteCreate.OnConflict
// documentation for more info.
func (u *SiteUpsertOne) Update(set func(*SiteUpsert)) *SiteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetRetired sets the "retired" field.
func (u *SiteUpsertOne) SetRetired(v bool) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetRetired(v)
	})
}

// UpdateRetired sets the "retired" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateRetired() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateRetired()
	})
}

// SetManifestVersion sets the "manifest_version" field.
func (u *SiteUpsertOne) SetManifestVersion(v uint64) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestVersion(v)
	})
}

// AddManifestVersion adds v to the "manifest_version" field.
func (u *SiteUpsertOne) AddManifestVersion(v uint64) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.AddManifestVersion(v)
	})
}

// UpdateManifestVersion sets the "manifest_version" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateManifestVersion() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestVersion()
	})
}

// SetManifestBody sets the "manifest_body" field.
func (u *SiteUpsertOne) SetManifestBody(v []byte) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestBody(v)
	})
}

// UpdateManifestBody sets the "manifest_body" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateManifestBody() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestBody()
	})
}

// ClearManifestBody clears the value of the "manifest_body" field.
func (u *SiteUpsertOne) ClearManifestBody() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.ClearManifestBody()
	})
}

// SetManifestEtag sets the "manifest_etag" field.
func (u *SiteUpsertOne) SetManifestEtag(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestEtag(v)
	})
}

// UpdateManifestEtag sets the "manifest_etag" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateManifestEtag() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestEtag()
	})
}

// SetManifestBundle sets the "manifest_bundle" field.
func (u *SiteUpsertOne) SetManifestBundle(v string) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestBundle(v)
	})
}

// UpdateManifestBundle sets the "manifest_bundle" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateManifestBundle() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestBundle()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *SiteUpsertOne) SetTokenHash(v []byte) *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SiteUpsertOne) UpdateTokenHash() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SiteUpsertOne) ClearTokenHash() *SiteUpsertOne {
	return u.Update(func(s *SiteUpsert) {
		s.ClearTokenHash()
	})
}

// Exec executes the query.
func (u *SiteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SiteUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SiteUpsertOne.ID is not supported by MySQL driver. Use SiteUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SiteUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SiteCreateBulk is the builder for creating many Site entities in bulk.
type SiteCreateBulk struct {
	config
	err      error
	builders []*SiteCreate
	conflict []sql.ConflictOption
}

// Save creates the Site entities in the database.
func (_c *SiteCreateBulk) Save(ctx context.Context) ([]*Site, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Site, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteCreateBulk) SaveX(ctx context.Context) []*Site {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Site.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SiteUpsert) {
//			SetRetired(v+v).
//		}).
//		Exec(ctx)
func (_c *SiteCreateBulk) OnConflict(opts ...sql.ConflictOption) *SiteUpsertBulk {
	_c.conflict = opts
	return &SiteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SiteCreateBulk) OnConflictColumns(columns ...string) *SiteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SiteUpsertBulk{
		create: _c,
	}
}

// SiteUpsertBulk is the builder for "upsert"-ing
// a bulk of Site nodes.
type SiteUpsertBulk struct {
	create *SiteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(site.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SiteUpsertBulk) UpdateNewValues() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(site.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Site.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SiteUpsertBulk) Ignore() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SiteUpsertBulk) DoNothing() *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SiteCreateBulk.OnConflict
// documentation for more info.
func (u *SiteUpsertBulk) Update(set func(*SiteUpsert)) *SiteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SiteUpsert{UpdateSet: update})
	}))
	return u
}

// SetRetired sets the "retired" field.
func (u *SiteUpsertBulk) SetRetired(v bool) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetRetired(v)
	})
}

// UpdateRetired sets the "retired" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateRetired() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateRetired()
	})
}

// SetManifestVersion sets the "manifest_version" field.
func (u *SiteUpsertBulk) SetManifestVersion(v uint64) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestVersion(v)
	})
}

// AddManifestVersion adds v to the "manifest_version" field.
func (u *SiteUpsertBulk) AddManifestVersion(v uint64) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.AddManifestVersion(v)
	})
}

// UpdateManifestVersion sets the "manifest_version" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateManifestVersion() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestVersion()
	})
}

// SetManifestBody sets the "manifest_body" field.
func (u *SiteUpsertBulk) SetManifestBody(v []byte) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestBody(v)
	})
}

// UpdateManifestBody sets the "manifest_body" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateManifestBody() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestBody()
	})
}

// ClearManifestBody clears the value of the "manifest_body" field.
func (u *SiteUpsertBulk) ClearManifestBody() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.ClearManifestBody()
	})
}

// SetManifestEtag sets the "manifest_etag" field.
func (u *SiteUpsertBulk) SetManifestEtag(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestEtag(v)
	})
}

// UpdateManifestEtag sets the "manifest_etag" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateManifestEtag() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestEtag()
	})
}

// SetManifestBundle sets the "manifest_bundle" field.
func (u *SiteUpsertBulk) SetManifestBundle(v string) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetManifestBundle(v)
	})
}

// UpdateManifestBundle sets the "manifest_bundle" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateManifestBundle() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateManifestBundle()
	})
}

// SetTokenHash sets the "token_hash" field.
func (u *SiteUpsertBulk) SetTokenHash(v []byte) *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.SetTokenHash(v)
	})
}

// UpdateTokenHash sets the "token_hash" field to the value that was provided on create.
func (u *SiteUpsertBulk) UpdateTokenHash() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.UpdateTokenHash()
	})
}

// ClearTokenHash clears the value of the "token_hash" field.
func (u *SiteUpsertBulk) ClearTokenHash() *SiteUpsertBulk {
	return u.Update(func(s *SiteUpsert) {
		s.ClearTokenHash()
	})
}

// Exec executes the query.
func (u *SiteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SiteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SiteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SiteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
