// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Blob is the predicate function for blob builders.
type Blob func(*sql.Selector)

// Deployment is the predicate function for deployment builders.
type Deployment func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Publication is the predicate function for publication builders.
type Publication func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// Status is the predicate function for status builders.
type Status func(*sql.Selector)
