// Code generated by ent, DO NOT EDIT.

package site

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the site type in the database.
	Label = "site"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRetired holds the string denoting the retired field in the database.
	FieldRetired = "retired"
	// FieldManifestVersion holds the string denoting the manifest_version field in the database.
	FieldManifestVersion = "manifest_version"
	// FieldManifestBody holds the string denoting the manifest_body field in the database.
	FieldManifestBody = "manifest_body"
	// FieldManifestEtag holds the string denoting the manifest_etag field in the database.
	FieldManifestEtag = "manifest_etag"
	// FieldManifestBundle holds the string denoting the manifest_bundle field in the database.
	FieldManifestBundle = "manifest_bundle"
	// FieldTokenHash holds the string denoting the token_hash field in the database.
	FieldTokenHash = "token_hash"
	// EdgeDevices holds the string denoting the devices edge name in mutations.
	EdgeDevices = "devices"
	// EdgeDeployments holds the string denoting the deployments edge name in mutations.
	EdgeDeployments = "deployments"
	// EdgePublications holds the string denoting the publications edge name in mutations.
	EdgePublications = "publications"
	// Table holds the table name of the site in the database.
	Table = "co_sites"
	// DevicesTable is the table that holds the devices relation/edge.
	DevicesTable = "co_devices"
	// DevicesInverseTable is the table name for the Device entity.
	// It exists in this package in order to avoid circular dependency with the "device" package.
	DevicesInverseTable = "co_devices"
	// DevicesColumn is the table column denoting the devices relation/edge.
	DevicesColumn = "site_id"
	// DeploymentsTable is the table that holds the deployments relation/edge.
	DeploymentsTable = "co_deployments"
	// DeploymentsInverseTable is the table name for the Deployment entity.
	// It exists in this package in order to avoid circular dependency with the "deployment" package.
	DeploymentsInverseTable = "co_deployments"
	// DeploymentsColumn is the table column denoting the deployments relation/edge.
	DeploymentsColumn = "site_id"
	// PublicationsTable is the table that holds the publications relation/edge.
	PublicationsTable = "co_publications"
	// PublicationsInverseTable is the table name for the Publication entity.
	// It exists in this package in order to avoid circular dependency with the "publication" package.
	PublicationsInverseTable = "co_publications"
	// PublicationsColumn is the table column denoting the publications relation/edge.
	PublicationsColumn = "site_id"
)

// Columns holds all SQL columns for site fields.
var Columns = []string{
	FieldID,
	FieldRetired,
	FieldManifestVersion,
	FieldManifestBody,
	FieldManifestEtag,
	FieldManifestBundle,
	FieldTokenHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRetired holds the default value on creation for the "retired" field.
	DefaultRetired bool
	// DefaultManifestVersion holds the default value on creation for the "manifest_version" field.
	DefaultManifestVersion uint64
	// DefaultManifestEtag holds the default value on creation for the "manifest_etag" field.
	DefaultManifestEtag string
	// DefaultManifestBundle holds the default value on creation for the "manifest_bundle" field.
	DefaultManifestBundle string
)

// OrderOption defines the ordering options for the Site queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRetired orders the results by the retired field.
func ByRetired(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetired, opts...).ToFunc()
}

// ByManifestVersion orders the results by the manifest_version field.
func ByManifestVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestVersion, opts...).ToFunc()
}

// ByManifestEtag orders the results by the manifest_etag field.
func ByManifestEtag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestEtag, opts...).ToFunc()
}

// ByManifestBundle orders the results by the manifest_bundle field.
func ByManifestBundle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestBundle, opts...).ToFunc()
}

// ByDevicesCount orders the results by devices count.
func ByDevicesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDevicesStep(), opts...)
	}
}

// ByDevices orders the results by devices terms.
func ByDevices(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDevicesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDeploymentsCount orders the results by deployments count.
func ByDeploymentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeploymentsStep(), opts...)
	}
}

// ByDeployments orders the results by deployments terms.
func ByDeployments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeploymentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPublicationsCount orders the results by publications count.
func ByPublicationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPublicationsStep(), opts...)
	}
}

// ByPublications orders the results by publications terms.
func ByPublications(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublicationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDevicesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DevicesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
	)
}
func newDeploymentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeploymentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeploymentsTable, DeploymentsColumn),
	)
}
func newPublicationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublicationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PublicationsTable, PublicationsColumn),
	)
}
