// Code generated by ent, DO NOT EDIT.

package site

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldID, id))
}

// Retired applies equality check predicate on the "retired" field. It's identical to RetiredEQ.
func Retired(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldRetired, v))
}

// ManifestVersion applies equality check predicate on the "manifest_version" field. It's identical to ManifestVersionEQ.
func ManifestVersion(v uint64) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestVersion, v))
}

// ManifestBody applies equality check predicate on the "manifest_body" field. It's identical to ManifestBodyEQ.
func ManifestBody(v []byte) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestBody, v))
}

// ManifestEtag applies equality check predicate on the "manifest_etag" field. It's identical to ManifestEtagEQ.
func ManifestEtag(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestEtag, v))
}

// ManifestBundle applies equality check predicate on the "manifest_bundle" field. It's identical to ManifestBundleEQ.
func ManifestBundle(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestBundle, v))
}

// TokenHash applies equality check predicate on the "token_hash" field. It's identical to TokenHashEQ.
func TokenHash(v []byte) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldTokenHash, v))
}

// RetiredEQ applies the EQ predicate on the "retired" field.
func RetiredEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldRetired, v))
}

// RetiredNEQ applies the NEQ predicate on the "retired" field.
func RetiredNEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldRetired, v))
}

// ManifestVersionEQ applies the EQ predicate on the "manifest_version" field.
func ManifestVersionEQ(v uint64) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestVersion, v))
}

// ManifestVersionNEQ applies the NEQ predicate on the "manifest_version" field.
func ManifestVersionNEQ(v uint64) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldManifestVersion, v))
}

// ManifestVersionIn applies the In predicate on the "manifest_version" field.
func ManifestVersionIn(vs ...uint64) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldManifestVersion, vs...))
}

// ManifestVersionNotIn applies the NotIn predicate on the "manifest_version" field.
func ManifestVersionNotIn(vs ...uint64) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldManifestVersion, vs...))
}

// ManifestVersionGT applies the GT predicate on the "manifest_version" field.
func ManifestVersionGT(v uint64) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldManifestVersion, v))
}

// ManifestVersionGTE applies the GTE predicate on the "manifest_version" field.
func ManifestVersionGTE(v uint64) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldManifestVersion, v))
}

// ManifestVersionLT applies the LT predicate on the "manifest_version" field.
func ManifestVersionLT(v uint64) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldManifestVersion, v))
}

// ManifestVersionLTE applies the LTE predicate on the "manifest_version" field.
func ManifestVersionLTE(v uint64) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldManifestVersion, v))
}

// ManifestBodyEQ applies the EQ predicate on the "manifest_body" field.
func ManifestBodyEQ(v []byte) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestBody, v))
}

// ManifestBodyNEQ applies the NEQ predicate on the "manifest_body" field.
func ManifestBodyNEQ(v []byte) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldManifestBody, v))
}

// ManifestBodyIn applies the In predicate on the "manifest_body" field.
func ManifestBodyIn(vs ...[]byte) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldManifestBody, vs...))
}

// ManifestBodyNotIn applies the NotIn predicate on the "manifest_body" field.
func ManifestBodyNotIn(vs ...[]byte) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldManifestBody, vs...))
}

// ManifestBodyGT applies the GT predicate on the "manifest_body" field.
func ManifestBodyGT(v []byte) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldManifestBody, v))
}

// ManifestBodyGTE applies the GTE predicate on the "manifest_body" field.
func ManifestBodyGTE(v []byte) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldManifestBody, v))
}

// ManifestBodyLT applies the LT predicate on the "manifest_body" field.
func ManifestBodyLT(v []byte) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldManifestBody, v))
}

// ManifestBodyLTE applies the LTE predicate on the "manifest_body" field.
func ManifestBodyLTE(v []byte) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldManifestBody, v))
}

// ManifestBodyIsNil applies the IsNil predicate on the "manifest_body" field.
func ManifestBodyIsNil() predicate.Site {
	return predicate.Site(sql.FieldIsNull(FieldManifestBody))
}

// ManifestBodyNotNil applies the NotNil predicate on the "manifest_body" field.
func ManifestBodyNotNil() predicate.Site {
	return predicate.Site(sql.FieldNotNull(FieldManifestBody))
}

// ManifestEtagEQ applies the EQ predicate on the "manifest_etag" field.
func ManifestEtagEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestEtag, v))
}

// ManifestEtagNEQ applies the NEQ predicate on the "manifest_etag" field.
func ManifestEtagNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldManifestEtag, v))
}

// ManifestEtagIn applies the In predicate on the "manifest_etag" field.
func ManifestEtagIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldManifestEtag, vs...))
}

// ManifestEtagNotIn applies the NotIn predicate on the "manifest_etag" field.
func ManifestEtagNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldManifestEtag, vs...))
}

// ManifestEtagGT applies the GT predicate on the "manifest_etag" field.
func ManifestEtagGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldManifestEtag, v))
}

// ManifestEtagGTE applies the GTE predicate on the "manifest_etag" field.
func ManifestEtagGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldManifestEtag, v))
}

// ManifestEtagLT applies the LT predicate on the "manifest_etag" field.
func ManifestEtagLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldManifestEtag, v))
}

// ManifestEtagLTE applies the LTE predicate on the "manifest_etag" field.
func ManifestEtagLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldManifestEtag, v))
}

// ManifestEtagContains applies the Contains predicate on the "manifest_etag" field.
func ManifestEtagContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldManifestEtag, v))
}

// ManifestEtagHasPrefix applies the HasPrefix predicate on the "manifest_etag" field.
func ManifestEtagHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldManifestEtag, v))
}

// ManifestEtagHasSuffix applies the HasSuffix predicate on the "manifest_etag" field.
func ManifestEtagHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldManifestEtag, v))
}

// ManifestEtagEqualFold applies the EqualFold predicate on the "manifest_etag" field.
func ManifestEtagEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldManifestEtag, v))
}

// ManifestEtagContainsFold applies the ContainsFold predicate on the "manifest_etag" field.
func ManifestEtagContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldManifestEtag, v))
}

// ManifestBundleEQ applies the EQ predicate on the "manifest_bundle" field.
func ManifestBundleEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldManifestBundle, v))
}

// ManifestBundleNEQ applies the NEQ predicate on the "manifest_bundle" field.
func ManifestBundleNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldManifestBundle, v))
}

// ManifestBundleIn applies the In predicate on the "manifest_bundle" field.
func ManifestBundleIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldManifestBundle, vs...))
}

// ManifestBundleNotIn applies the NotIn predicate on the "manifest_bundle" field.
func ManifestBundleNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldManifestBundle, vs...))
}

// ManifestBundleGT applies the GT predicate on the "manifest_bundle" field.
func ManifestBundleGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldManifestBundle, v))
}

// ManifestBundleGTE applies the GTE predicate on the "manifest_bundle" field.
func ManifestBundleGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldManifestBundle, v))
}

// ManifestBundleLT applies the LT predicate on the "manifest_bundle" field.
func ManifestBundleLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldManifestBundle, v))
}

// ManifestBundleLTE applies the LTE predicate on the "manifest_bundle" field.
func ManifestBundleLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldManifestBundle, v))
}

// ManifestBundleContains applies the Contains predicate on the "manifest_bundle" field.
func ManifestBundleContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldManifestBundle, v))
}

// ManifestBundleHasPrefix applies the HasPrefix predicate on the "manifest_bundle" field.
func ManifestBundleHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldManifestBundle, v))
}

// ManifestBundleHasSuffix applies the HasSuffix predicate on the "manifest_bundle" field.
func ManifestBundleHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldManifestBundle, v))
}

// ManifestBundleEqualFold applies the EqualFold predicate on the "manifest_bundle" field.
func ManifestBundleEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldManifestBundle, v))
}

// ManifestBundleContainsFold applies the ContainsFold predicate on the "manifest_bundle" field.
func ManifestBundleContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldManifestBundle, v))
}

// TokenHashEQ applies the EQ predicate on the "token_hash" field.
func TokenHashEQ(v []byte) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldTokenHash, v))
}

// TokenHashNEQ applies the NEQ predicate on the "token_hash" field.
func TokenHashNEQ(v []byte) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldTokenHash, v))
}

// TokenHashIn applies the In predicate on the "token_hash" field.
func TokenHashIn(vs ...[]byte) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldTokenHash, vs...))
}

// TokenHashNotIn applies the NotIn predicate on the "token_hash" field.
func TokenHashNotIn(vs ...[]byte) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldTokenHash, vs...))
}

// TokenHashGT applies the GT predicate on the "token_hash" field.
func TokenHashGT(v []byte) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldTokenHash, v))
}

// TokenHashGTE applies the GTE predicate on the "token_hash" field.
func TokenHashGTE(v []byte) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldTokenHash, v))
}

// TokenHashLT applies the LT predicate on the "token_hash" field.
func TokenHashLT(v []byte) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldTokenHash, v))
}

// TokenHashLTE applies the LTE predicate on the "token_hash" field.
func TokenHashLTE(v []byte) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldTokenHash, v))
}

// TokenHashIsNil applies the IsNil predicate on the "token_hash" field.
func TokenHashIsNil() predicate.Site {
	return predicate.Site(sql.FieldIsNull(FieldTokenHash))
}

// TokenHashNotNil applies the NotNil predicate on the "token_hash" field.
func TokenHashNotNil() predicate.Site {
	return predicate.Site(sql.FieldNotNull(FieldTokenHash))
}

// HasDevices applies the HasEdge predicate on the "devices" edge.
func HasDevices() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DevicesTable, DevicesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDevicesWith applies the HasEdge predicate on the "devices" edge with a given conditions (other predicates).
func HasDevicesWith(preds ...predicate.Device) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newDevicesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeployments applies the HasEdge predicate on the "deployments" edge.
func HasDeployments() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeploymentsTable, DeploymentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeploymentsWith applies the HasEdge predicate on the "deployments" edge with a given conditions (other predicates).
func HasDeploymentsWith(preds ...predicate.Deployment) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newDeploymentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPublications applies the HasEdge predicate on the "publications" edge.
func HasPublications() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PublicationsTable, PublicationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPublicationsWith applies the HasEdge predicate on the "publications" edge with a given conditions (other predicates).
func HasPublicationsWith(preds ...predicate.Publication) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newPublicationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Site) predicate.Site {
	return predicate.Site(sql.NotPredicates(p))
}
