// Code generated by ent, DO NOT EDIT.

package deployment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the deployment type in the database.
	Label = "deployment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSiteID holds the string denoting the site_id field in the database.
	FieldSiteID = "site_id"
	// FieldTarget holds the string denoting the target field in the database.
	FieldTarget = "target"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldProfile holds the string denoting the profile field in the database.
	FieldProfile = "profile"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNamespace holds the string denoting the namespace field in the database.
	FieldNamespace = "namespace"
	// FieldParameters holds the string denoting the parameters field in the database.
	FieldParameters = "parameters"
	// FieldDigest holds the string denoting the digest field in the database.
	FieldDigest = "digest"
	// FieldDigestVersion holds the string denoting the digest_version field in the database.
	FieldDigestVersion = "digest_version"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldDeletedVersion holds the string denoting the deleted_version field in the database.
	FieldDeletedVersion = "deleted_version"
	// FieldRemoved holds the string denoting the removed field in the database.
	FieldRemoved = "removed"
	// FieldReported holds the string denoting the reported field in the database.
	FieldReported = "reported"
	// FieldCurrentStatus holds the string denoting the current_status field in the database.
	FieldCurrentStatus = "current_status"
	// EdgeSite holds the string denoting the site edge name in mutations.
	EdgeSite = "site"
	// EdgeStatuses holds the string denoting the statuses edge name in mutations.
	EdgeStatuses = "statuses"
	// Table holds the table name of the deployment in the database.
	Table = "co_deployments"
	// SiteTable is the table that holds the site relation/edge.
	SiteTable = "co_deployments"
	// SiteInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	SiteInverseTable = "co_sites"
	// SiteColumn is the table column denoting the site relation/edge.
	SiteColumn = "site_id"
	// StatusesTable is the table that holds the statuses relation/edge.
	StatusesTable = "co_statuses"
	// StatusesInverseTable is the table name for the Status entity.
	// It exists in this package in order to avoid circular dependency with the "status" package.
	StatusesInverseTable = "co_statuses"
	// StatusesColumn is the table column denoting the statuses relation/edge.
	StatusesColumn = "deployment_id"
)

// Columns holds all SQL columns for deployment fields.
var Columns = []string{
	FieldID,
	FieldSiteID,
	FieldTarget,
	FieldAppID,
	FieldAppVersion,
	FieldProfile,
	FieldName,
	FieldNamespace,
	FieldParameters,
	FieldDigest,
	FieldDigestVersion,
	FieldDeleted,
	FieldDeletedVersion,
	FieldRemoved,
	FieldReported,
	FieldCurrentStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReported holds the default value on creation for the "reported" field.
	DefaultReported bool
)

// OrderOption defines the ordering options for the Deployment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySiteID orders the results by the site_id field.
func BySiteID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteID, opts...).ToFunc()
}

// ByTarget orders the results by the target field.
func ByTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTarget, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByProfile orders the results by the profile field.
func ByProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfile, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNamespace orders the results by the namespace field.
func ByNamespace(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNamespace, opts...).ToFunc()
}

// ByDigest orders the results by the digest field.
func ByDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigest, opts...).ToFunc()
}

// ByDigestVersion orders the results by the digest_version field.
func ByDigestVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigestVersion, opts...).ToFunc()
}

// ByDeleted orders the results by the deleted field.
func ByDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleted, opts...).ToFunc()
}

// ByDeletedVersion orders the results by the deleted_version field.
func ByDeletedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedVersion, opts...).ToFunc()
}

// ByRemoved orders the results by the removed field.
func ByRemoved(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoved, opts...).ToFunc()
}

// ByReported orders the results by the reported field.
func ByReported(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReported, opts...).ToFunc()
}

// BySiteField orders the results by site field.
func BySiteField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSiteStep(), sql.OrderByField(field, opts...))
	}
}

// ByStatusesCount orders the results by statuses count.
func ByStatusesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatusesStep(), opts...)
	}
}

// ByStatuses orders the results by statuses terms.
func ByStatuses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatusesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSiteStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SiteInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
	)
}
func newStatusesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatusesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StatusesTable, StatusesColumn),
	)
}
