// Code generated by ent, DO NOT EDIT.

package deployment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldSiteID, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldTarget, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldAppID, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldAppVersion, v))
}

// Profile applies equality check predicate on the "profile" field. It's identical to ProfileEQ.
func Profile(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldProfile, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldName, v))
}

// Namespace applies equality check predicate on the "namespace" field. It's identical to NamespaceEQ.
func Namespace(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldNamespace, v))
}

// Parameters applies equality check predicate on the "parameters" field. It's identical to ParametersEQ.
func Parameters(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldParameters, v))
}

// Digest applies equality check predicate on the "digest" field. It's identical to DigestEQ.
func Digest(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDigest, v))
}

// DigestVersion applies equality check predicate on the "digest_version" field. It's identical to DigestVersionEQ.
func DigestVersion(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDigestVersion, v))
}

// Deleted applies equality check predicate on the "deleted" field. It's identical to DeletedEQ.
func Deleted(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDeleted, v))
}

// DeletedVersion applies equality check predicate on the "deleted_version" field. It's identical to DeletedVersionEQ.
func DeletedVersion(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDeletedVersion, v))
}

// Removed applies equality check predicate on the "removed" field. It's identical to RemovedEQ.
func Removed(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldRemoved, v))
}

// Reported applies equality check predicate on the "reported" field. It's identical to ReportedEQ.
func Reported(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldReported, v))
}

// CurrentStatus applies equality check predicate on the "current_status" field. It's identical to CurrentStatusEQ.
func CurrentStatus(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldCurrentStatus, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldSiteID, vs...))
}

// SiteIDGT applies the GT predicate on the "site_id" field.
func SiteIDGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldSiteID, v))
}

// SiteIDGTE applies the GTE predicate on the "site_id" field.
func SiteIDGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldSiteID, v))
}

// SiteIDLT applies the LT predicate on the "site_id" field.
func SiteIDLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldSiteID, v))
}

// SiteIDLTE applies the LTE predicate on the "site_id" field.
func SiteIDLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldSiteID, v))
}

// SiteIDContains applies the Contains predicate on the "site_id" field.
func SiteIDContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldSiteID, v))
}

// SiteIDHasPrefix applies the HasPrefix predicate on the "site_id" field.
func SiteIDHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldSiteID, v))
}

// SiteIDHasSuffix applies the HasSuffix predicate on the "site_id" field.
func SiteIDHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldSiteID, v))
}

// SiteIDEqualFold applies the EqualFold predicate on the "site_id" field.
func SiteIDEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldSiteID, v))
}

// SiteIDContainsFold applies the ContainsFold predicate on the "site_id" field.
func SiteIDContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldSiteID, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldTarget, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldAppID, v))
}

// AppIDContains applies the Contains predicate on the "app_id" field.
func AppIDContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldAppID, v))
}

// AppIDHasPrefix applies the HasPrefix predicate on the "app_id" field.
func AppIDHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldAppID, v))
}

// AppIDHasSuffix applies the HasSuffix predicate on the "app_id" field.
func AppIDHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldAppID, v))
}

// AppIDEqualFold applies the EqualFold predicate on the "app_id" field.
func AppIDEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldAppID, v))
}

// AppIDContainsFold applies the ContainsFold predicate on the "app_id" field.
func AppIDContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldAppID, v))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldAppVersion, v))
}

// ProfileEQ applies the EQ predicate on the "profile" field.
func ProfileEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldProfile, v))
}

// ProfileNEQ applies the NEQ predicate on the "profile" field.
func ProfileNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldProfile, v))
}

// ProfileIn applies the In predicate on the "profile" field.
func ProfileIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldProfile, vs...))
}

// ProfileNotIn applies the NotIn predicate on the "profile" field.
func ProfileNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldProfile, vs...))
}

// ProfileGT applies the GT predicate on the "profile" field.
func ProfileGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldProfile, v))
}

// ProfileGTE applies the GTE predicate on the "profile" field.
func ProfileGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldProfile, v))
}

// ProfileLT applies the LT predicate on the "profile" field.
func ProfileLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldProfile, v))
}

// ProfileLTE applies the LTE predicate on the "profile" field.
func ProfileLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldProfile, v))
}

// ProfileContains applies the Contains predicate on the "profile" field.
func ProfileContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldProfile, v))
}

// ProfileHasPrefix applies the HasPrefix predicate on the "profile" field.
func ProfileHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldProfile, v))
}

// ProfileHasSuffix applies the HasSuffix predicate on the "profile" field.
func ProfileHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldProfile, v))
}

// ProfileEqualFold applies the EqualFold predicate on the "profile" field.
func ProfileEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldProfile, v))
}

// ProfileContainsFold applies the ContainsFold predicate on the "profile" field.
func ProfileContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldProfile, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldName, v))
}

// NamespaceEQ applies the EQ predicate on the "namespace" field.
func NamespaceEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldNamespace, v))
}

// NamespaceNEQ applies the NEQ predicate on the "namespace" field.
func NamespaceNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldNamespace, v))
}

// NamespaceIn applies the In predicate on the "namespace" field.
func NamespaceIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldNamespace, vs...))
}

// NamespaceNotIn applies the NotIn predicate on the "namespace" field.
func NamespaceNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldNamespace, vs...))
}

// NamespaceGT applies the GT predicate on the "namespace" field.
func NamespaceGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldNamespace, v))
}

// NamespaceGTE applies the GTE predicate on the "namespace" field.
func NamespaceGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldNamespace, v))
}

// NamespaceLT applies the LT predicate on the "namespace" field.
func NamespaceLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldNamespace, v))
}

// NamespaceLTE applies the LTE predicate on the "namespace" field.
func NamespaceLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldNamespace, v))
}

// NamespaceContains applies the Contains predicate on the "namespace" field.
func NamespaceContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldNamespace, v))
}

// NamespaceHasPrefix applies the HasPrefix predicate on the "namespace" field.
func NamespaceHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldNamespace, v))
}

// NamespaceHasSuffix applies the HasSuffix predicate on the "namespace" field.
func NamespaceHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldNamespace, v))
}

// NamespaceEqualFold applies the EqualFold predicate on the "namespace" field.
func NamespaceEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldNamespace, v))
}

// NamespaceContainsFold applies the ContainsFold predicate on the "namespace" field.
func NamespaceContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldNamespace, v))
}

// ParametersEQ applies the EQ predicate on the "parameters" field.
func ParametersEQ(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldParameters, v))
}

// ParametersNEQ applies the NEQ predicate on the "parameters" field.
func ParametersNEQ(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldParameters, v))
}

// ParametersIn applies the In predicate on the "parameters" field.
func ParametersIn(vs ...[]byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldParameters, vs...))
}

// ParametersNotIn applies the NotIn predicate on the "parameters" field.
func ParametersNotIn(vs ...[]byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldParameters, vs...))
}

// ParametersGT applies the GT predicate on the "parameters" field.
func ParametersGT(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldParameters, v))
}

// ParametersGTE applies the GTE predicate on the "parameters" field.
func ParametersGTE(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldParameters, v))
}

// ParametersLT applies the LT predicate on the "parameters" field.
func ParametersLT(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldParameters, v))
}

// ParametersLTE applies the LTE predicate on the "parameters" field.
func ParametersLTE(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldParameters, v))
}

// DigestEQ applies the EQ predicate on the "digest" field.
func DigestEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDigest, v))
}

// DigestNEQ applies the NEQ predicate on the "digest" field.
func DigestNEQ(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldDigest, v))
}

// DigestIn applies the In predicate on the "digest" field.
func DigestIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldDigest, vs...))
}

// DigestNotIn applies the NotIn predicate on the "digest" field.
func DigestNotIn(vs ...string) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldDigest, vs...))
}

// DigestGT applies the GT predicate on the "digest" field.
func DigestGT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldDigest, v))
}

// DigestGTE applies the GTE predicate on the "digest" field.
func DigestGTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldDigest, v))
}

// DigestLT applies the LT predicate on the "digest" field.
func DigestLT(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldDigest, v))
}

// DigestLTE applies the LTE predicate on the "digest" field.
func DigestLTE(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldDigest, v))
}

// DigestContains applies the Contains predicate on the "digest" field.
func DigestContains(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContains(FieldDigest, v))
}

// DigestHasPrefix applies the HasPrefix predicate on the "digest" field.
func DigestHasPrefix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasPrefix(FieldDigest, v))
}

// DigestHasSuffix applies the HasSuffix predicate on the "digest" field.
func DigestHasSuffix(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldHasSuffix(FieldDigest, v))
}

// DigestEqualFold applies the EqualFold predicate on the "digest" field.
func DigestEqualFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldEqualFold(FieldDigest, v))
}

// DigestContainsFold applies the ContainsFold predicate on the "digest" field.
func DigestContainsFold(v string) predicate.Deployment {
	return predicate.Deployment(sql.FieldContainsFold(FieldDigest, v))
}

// DigestVersionEQ applies the EQ predicate on the "digest_version" field.
func DigestVersionEQ(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDigestVersion, v))
}

// DigestVersionNEQ applies the NEQ predicate on the "digest_version" field.
func DigestVersionNEQ(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldDigestVersion, v))
}

// DigestVersionIn applies the In predicate on the "digest_version" field.
func DigestVersionIn(vs ...uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldDigestVersion, vs...))
}

// DigestVersionNotIn applies the NotIn predicate on the "digest_version" field.
func DigestVersionNotIn(vs ...uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldDigestVersion, vs...))
}

// DigestVersionGT applies the GT predicate on the "digest_version" field.
func DigestVersionGT(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldDigestVersion, v))
}

// DigestVersionGTE applies the GTE predicate on the "digest_version" field.
func DigestVersionGTE(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldDigestVersion, v))
}

// DigestVersionLT applies the LT predicate on the "digest_version" field.
func DigestVersionLT(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldDigestVersion, v))
}

// DigestVersionLTE applies the LTE predicate on the "digest_version" field.
func DigestVersionLTE(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldDigestVersion, v))
}

// DeletedEQ applies the EQ predicate on the "deleted" field.
func DeletedEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDeleted, v))
}

// DeletedNEQ applies the NEQ predicate on the "deleted" field.
func DeletedNEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldDeleted, v))
}

// DeletedVersionEQ applies the EQ predicate on the "deleted_version" field.
func DeletedVersionEQ(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldDeletedVersion, v))
}

// DeletedVersionNEQ applies the NEQ predicate on the "deleted_version" field.
func DeletedVersionNEQ(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldDeletedVersion, v))
}

// DeletedVersionIn applies the In predicate on the "deleted_version" field.
func DeletedVersionIn(vs ...uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldDeletedVersion, vs...))
}

// DeletedVersionNotIn applies the NotIn predicate on the "deleted_version" field.
func DeletedVersionNotIn(vs ...uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldDeletedVersion, vs...))
}

// DeletedVersionGT applies the GT predicate on the "deleted_version" field.
func DeletedVersionGT(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldDeletedVersion, v))
}

// DeletedVersionGTE applies the GTE predicate on the "deleted_version" field.
func DeletedVersionGTE(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldDeletedVersion, v))
}

// DeletedVersionLT applies the LT predicate on the "deleted_version" field.
func DeletedVersionLT(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldDeletedVersion, v))
}

// DeletedVersionLTE applies the LTE predicate on the "deleted_version" field.
func DeletedVersionLTE(v uint64) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldDeletedVersion, v))
}

// RemovedEQ applies the EQ predicate on the "removed" field.
func RemovedEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldRemoved, v))
}

// RemovedNEQ applies the NEQ predicate on the "removed" field.
func RemovedNEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldRemoved, v))
}

// ReportedEQ applies the EQ predicate on the "reported" field.
func ReportedEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldReported, v))
}

// ReportedNEQ applies the NEQ predicate on the "reported" field.
func ReportedNEQ(v bool) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldReported, v))
}

// CurrentStatusEQ applies the EQ predicate on the "current_status" field.
func CurrentStatusEQ(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldEQ(FieldCurrentStatus, v))
}

// CurrentStatusNEQ applies the NEQ predicate on the "current_status" field.
func CurrentStatusNEQ(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldNEQ(FieldCurrentStatus, v))
}

// CurrentStatusIn applies the In predicate on the "current_status" field.
func CurrentStatusIn(vs ...[]byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldIn(FieldCurrentStatus, vs...))
}

// CurrentStatusNotIn applies the NotIn predicate on the "current_status" field.
func CurrentStatusNotIn(vs ...[]byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldNotIn(FieldCurrentStatus, vs...))
}

// CurrentStatusGT applies the GT predicate on the "current_status" field.
func CurrentStatusGT(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldGT(FieldCurrentStatus, v))
}

// CurrentStatusGTE applies the GTE predicate on the "current_status" field.
func CurrentStatusGTE(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldGTE(FieldCurrentStatus, v))
}

// CurrentStatusLT applies the LT predicate on the "current_status" field.
func CurrentStatusLT(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldLT(FieldCurrentStatus, v))
}

// CurrentStatusLTE applies the LTE predicate on the "current_status" field.
func CurrentStatusLTE(v []byte) predicate.Deployment {
	return predicate.Deployment(sql.FieldLTE(FieldCurrentStatus, v))
}

// CurrentStatusIsNil applies the IsNil predicate on the "current_status" field.
func CurrentStatusIsNil() predicate.Deployment {
	return predicate.Deployment(sql.FieldIsNull(FieldCurrentStatus))
}

// CurrentStatusNotNil applies the NotNil predicate on the "current_status" field.
func CurrentStatusNotNil() predicate.Deployment {
	return predicate.Deployment(sql.FieldNotNull(FieldCurrentStatus))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.Deployment {
	return predicate.Deployment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.Deployment {
	return predicate.Deployment(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStatuses applies the HasEdge predicate on the "statuses" edge.
func HasStatuses() predicate.Deployment {
	return predicate.Deployment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatusesTable, StatusesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatusesWith applies the HasEdge predicate on the "statuses" edge with a given conditions (other predicates).
func HasStatusesWith(preds ...predicate.Status) predicate.Deployment {
	return predicate.Deployment(func(s *sql.Selector) {
		step := newStatusesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deployment) predicate.Deployment {
	return predicate.Deployment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deployment) predicate.Deployment {
	return predicate.Deployment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deployment) predicate.Deployment {
	return predicate.Deployment(sql.NotPredicates(p))
}
