// Code generated by ent, DO NOT EDIT.

package publication

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Publication {
	return predicate.Publication(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Publication {
	return predicate.Publication(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Publication {
	return predicate.Publication(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Publication {
	return predicate.Publication(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Publication {
	return predicate.Publication(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Publication {
	return predicate.Publication(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Publication {
	return predicate.Publication(sql.FieldLTE(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldSiteID, v))
}

// Bundle applies equality check predicate on the "bundle" field. It's identical to BundleEQ.
func Bundle(v bool) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldBundle, v))
}

// DeploymentID applies equality check predicate on the "deployment_id" field. It's identical to DeploymentIDEQ.
func DeploymentID(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldDeploymentID, v))
}

// Digest applies equality check predicate on the "digest" field. It's identical to DigestEQ.
func Digest(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldDigest, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v string) predicate.Publication {
	return predicate.Publication(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...string) predicate.Publication {
	return predicate.Publication(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...string) predicate.Publication {
	return predicate.Publication(sql.FieldNotIn(FieldSiteID, vs...))
}

// SiteIDGT applies the GT predicate on the "site_id" field.
func SiteIDGT(v string) predicate.Publication {
	return predicate.Publication(sql.FieldGT(FieldSiteID, v))
}

// SiteIDGTE applies the GTE predicate on the "site_id" field.
func SiteIDGTE(v string) predicate.Publication {
	return predicate.Publication(sql.FieldGTE(FieldSiteID, v))
}

// SiteIDLT applies the LT predicate on the "site_id" field.
func SiteIDLT(v string) predicate.Publication {
	return predicate.Publication(sql.FieldLT(FieldSiteID, v))
}

// SiteIDLTE applies the LTE predicate on the "site_id" field.
func SiteIDLTE(v string) predicate.Publication {
	return predicate.Publication(sql.FieldLTE(FieldSiteID, v))
}

// SiteIDContains applies the Contains predicate on the "site_id" field.
func SiteIDContains(v string) predicate.Publication {
	return predicate.Publication(sql.FieldContains(FieldSiteID, v))
}

// SiteIDHasPrefix applies the HasPrefix predicate on the "site_id" field.
func SiteIDHasPrefix(v string) predicate.Publication {
	return predicate.Publication(sql.FieldHasPrefix(FieldSiteID, v))
}

// SiteIDHasSuffix applies the HasSuffix predicate on the "site_id" field.
func SiteIDHasSuffix(v string) predicate.Publication {
	return predicate.Publication(sql.FieldHasSuffix(FieldSiteID, v))
}

// SiteIDEqualFold applies the EqualFold predicate on the "site_id" field.
func SiteIDEqualFold(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEqualFold(FieldSiteID, v))
}

// SiteIDContainsFold applies the ContainsFold predicate on the "site_id" field.
func SiteIDContainsFold(v string) predicate.Publication {
	return predicate.Publication(sql.FieldContainsFold(FieldSiteID, v))
}

// BundleEQ applies the EQ predicate on the "bundle" field.
func BundleEQ(v bool) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldBundle, v))
}

// BundleNEQ applies the NEQ predicate on the "bundle" field.
func BundleNEQ(v bool) predicate.Publication {
	return predicate.Publication(sql.FieldNEQ(FieldBundle, v))
}

// DeploymentIDEQ applies the EQ predicate on the "deployment_id" field.
func DeploymentIDEQ(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldDeploymentID, v))
}

// DeploymentIDNEQ applies the NEQ predicate on the "deployment_id" field.
func DeploymentIDNEQ(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldNEQ(FieldDeploymentID, v))
}

// DeploymentIDIn applies the In predicate on the "deployment_id" field.
func DeploymentIDIn(vs ...uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldIn(FieldDeploymentID, vs...))
}

// DeploymentIDNotIn applies the NotIn predicate on the "deployment_id" field.
func DeploymentIDNotIn(vs ...uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldNotIn(FieldDeploymentID, vs...))
}

// DeploymentIDGT applies the GT predicate on the "deployment_id" field.
func DeploymentIDGT(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldGT(FieldDeploymentID, v))
}

// DeploymentIDGTE applies the GTE predicate on the "deployment_id" field.
func DeploymentIDGTE(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldGTE(FieldDeploymentID, v))
}

// DeploymentIDLT applies the LT predicate on the "deployment_id" field.
func DeploymentIDLT(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldLT(FieldDeploymentID, v))
}

// DeploymentIDLTE applies the LTE predicate on the "deployment_id" field.
func DeploymentIDLTE(v uuid.UUID) predicate.Publication {
	return predicate.Publication(sql.FieldLTE(FieldDeploymentID, v))
}

// DigestEQ applies the EQ predicate on the "digest" field.
func DigestEQ(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEQ(FieldDigest, v))
}

// DigestNEQ applies the NEQ predicate on the "digest" field.
func DigestNEQ(v string) predicate.Publication {
	return predicate.Publication(sql.FieldNEQ(FieldDigest, v))
}

// DigestIn applies the In predicate on the "digest" field.
func DigestIn(vs ...string) predicate.Publication {
	return predicate.Publication(sql.FieldIn(FieldDigest, vs...))
}

// DigestNotIn applies the NotIn predicate on the "digest" field.
func DigestNotIn(vs ...string) predicate.Publication {
	return predicate.Publication(sql.FieldNotIn(FieldDigest, vs...))
}

// DigestGT applies the GT predicate on the "digest" field.
func DigestGT(v string) predicate.Publication {
	return predicate.Publication(sql.FieldGT(FieldDigest, v))
}

// DigestGTE applies the GTE predicate on the "digest" field.
func DigestGTE(v string) predicate.Publication {
	return predicate.Publication(sql.FieldGTE(FieldDigest, v))
}

// DigestLT applies the LT predicate on the "digest" field.
func DigestLT(v string) predicate.Publication {
	return predicate.Publication(sql.FieldLT(FieldDigest, v))
}

// DigestLTE applies the LTE predicate on the "digest" field.
func DigestLTE(v string) predicate.Publication {
	return predicate.Publication(sql.FieldLTE(FieldDigest, v))
}

// DigestContains applies the Contains predicate on the "digest" field.
func DigestContains(v string) predicate.Publication {
	return predicate.Publication(sql.FieldContains(FieldDigest, v))
}

// DigestHasPrefix applies the HasPrefix predicate on the "digest" field.
func DigestHasPrefix(v string) predicate.Publication {
	return predicate.Publication(sql.FieldHasPrefix(FieldDigest, v))
}

// DigestHasSuffix applies the HasSuffix predicate on the "digest" field.
func DigestHasSuffix(v string) predicate.Publication {
	return predicate.Publication(sql.FieldHasSuffix(FieldDigest, v))
}

// DigestEqualFold applies the EqualFold predicate on the "digest" field.
func DigestEqualFold(v string) predicate.Publication {
	return predicate.Publication(sql.FieldEqualFold(FieldDigest, v))
}

// DigestContainsFold applies the ContainsFold predicate on the "digest" field.
func DigestContainsFold(v string) predicate.Publication {
	return predicate.Publication(sql.FieldContainsFold(FieldDigest, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.Publication {
	return predicate.Publication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.Publication {
	return predicate.Publication(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Publication) predicate.Publication {
	return predicate.Publication(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Publication) predicate.Publication {
	return predicate.Publication(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Publication) predicate.Publication {
	return predicate.Publication(sql.NotPredicates(p))
}
