// Code generated by ent, DO NOT EDIT.

package device

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/balaji-balu/ieo/internal/co/store/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldID, id))
}

// SiteID applies equality check predicate on the "site_id" field. It's identical to SiteIDEQ.
func SiteID(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSiteID, v))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldHost, v))
}

// Capabilities applies equality check predicate on the "capabilities" field. It's identical to CapabilitiesEQ.
func Capabilities(v []byte) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCapabilities, v))
}

// SiteIDEQ applies the EQ predicate on the "site_id" field.
func SiteIDEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldSiteID, v))
}

// SiteIDNEQ applies the NEQ predicate on the "site_id" field.
func SiteIDNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldSiteID, v))
}

// SiteIDIn applies the In predicate on the "site_id" field.
func SiteIDIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldSiteID, vs...))
}

// SiteIDNotIn applies the NotIn predicate on the "site_id" field.
func SiteIDNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldSiteID, vs...))
}

// SiteIDGT applies the GT predicate on the "site_id" field.
func SiteIDGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldSiteID, v))
}

// SiteIDGTE applies the GTE predicate on the "site_id" field.
func SiteIDGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldSiteID, v))
}

// SiteIDLT applies the LT predicate on the "site_id" field.
func SiteIDLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldSiteID, v))
}

// SiteIDLTE applies the LTE predicate on the "site_id" field.
func SiteIDLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldSiteID, v))
}

// SiteIDContains applies the Contains predicate on the "site_id" field.
func SiteIDContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldSiteID, v))
}

// SiteIDHasPrefix applies the HasPrefix predicate on the "site_id" field.
func SiteIDHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldSiteID, v))
}

// SiteIDHasSuffix applies the HasSuffix predicate on the "site_id" field.
func SiteIDHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldSiteID, v))
}

// SiteIDEqualFold applies the EqualFold predicate on the "site_id" field.
func SiteIDEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldSiteID, v))
}

// SiteIDContainsFold applies the ContainsFold predicate on the "site_id" field.
func SiteIDContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldSiteID, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.Device {
	return predicate.Device(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.Device {
	return predicate.Device(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.Device {
	return predicate.Device(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.Device {
	return predicate.Device(sql.FieldContainsFold(FieldHost, v))
}

// CapabilitiesEQ applies the EQ predicate on the "capabilities" field.
func CapabilitiesEQ(v []byte) predicate.Device {
	return predicate.Device(sql.FieldEQ(FieldCapabilities, v))
}

// CapabilitiesNEQ applies the NEQ predicate on the "capabilities" field.
func CapabilitiesNEQ(v []byte) predicate.Device {
	return predicate.Device(sql.FieldNEQ(FieldCapabilities, v))
}

// CapabilitiesIn applies the In predicate on the "capabilities" field.
func CapabilitiesIn(vs ...[]byte) predicate.Device {
	return predicate.Device(sql.FieldIn(FieldCapabilities, vs...))
}

// CapabilitiesNotIn applies the NotIn predicate on the "capabilities" field.
func CapabilitiesNotIn(vs ...[]byte) predicate.Device {
	return predicate.Device(sql.FieldNotIn(FieldCapabilities, vs...))
}

// CapabilitiesGT applies the GT predicate on the "capabilities" field.
func CapabilitiesGT(v []byte) predicate.Device {
	return predicate.Device(sql.FieldGT(FieldCapabilities, v))
}

// CapabilitiesGTE applies the GTE predicate on the "capabilities" field.
func CapabilitiesGTE(v []byte) predicate.Device {
	return predicate.Device(sql.FieldGTE(FieldCapabilities, v))
}

// CapabilitiesLT applies the LT predicate on the "capabilities" field.
func CapabilitiesLT(v []byte) predicate.Device {
	return predicate.Device(sql.FieldLT(FieldCapabilities, v))
}

// CapabilitiesLTE applies the LTE predicate on the "capabilities" field.
func CapabilitiesLTE(v []byte) predicate.Device {
	return predicate.Device(sql.FieldLTE(FieldCapabilities, v))
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.Device {
	return predicate.Device(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Device) predicate.Device {
	return predicate.Device(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Device) predicate.Device {
	return predicate.Device(sql.NotPredicates(p))
}
