-- The CO store (SPEC §12, roadmap B4). Tables generated from ../ent/schema with
-- `go run entgo.io/ent/cmd/ent schema ./internal/co/store/postgres/ent/schema --dialect postgres --version 16`.

-- Create "co_apps" table
CREATE TABLE "co_apps" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "app_id" character varying NOT NULL,
  "version" character varying NOT NULL,
  "repository" character varying NOT NULL,
  "description" bytea NOT NULL,
  "digest" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "co_apps_app_id_version" to table: "co_apps"
CREATE UNIQUE INDEX "co_apps_app_id_version" ON "co_apps" ("app_id", "version");
-- Create "co_blobs" table
CREATE TABLE "co_blobs" (
  "id" character varying NOT NULL,
  "content" bytea NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "co_sites" table
CREATE TABLE "co_sites" (
  "id" character varying NOT NULL,
  "retired" boolean NOT NULL DEFAULT false,
  "manifest_version" bigint NOT NULL DEFAULT 0,
  "manifest_body" bytea NULL,
  "manifest_etag" character varying NOT NULL DEFAULT '',
  "manifest_bundle" character varying NOT NULL DEFAULT '',
  "token_hash" bytea NULL,
  PRIMARY KEY ("id")
);
-- Create index "co_sites_token_hash_key" to table: "co_sites"
CREATE UNIQUE INDEX "co_sites_token_hash_key" ON "co_sites" ("token_hash");
-- Create "co_deployments" table
CREATE TABLE "co_deployments" (
  "id" uuid NOT NULL,
  "target" character varying NOT NULL,
  "app_id" character varying NOT NULL,
  "app_version" character varying NOT NULL,
  "profile" character varying NOT NULL,
  "name" character varying NOT NULL,
  "namespace" character varying NOT NULL,
  "parameters" bytea NOT NULL,
  "digest" character varying NOT NULL,
  "digest_version" bigint NOT NULL,
  "deleted" boolean NOT NULL,
  "deleted_version" bigint NOT NULL,
  "removed" boolean NOT NULL,
  "reported" boolean NOT NULL DEFAULT false,
  "current_status" bytea NULL,
  "site_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "co_deployments_co_sites_deployments" FOREIGN KEY ("site_id") REFERENCES "co_sites" ("id") ON DELETE NO ACTION
);
-- Create index "co_deployments_site_id" to table: "co_deployments"
CREATE INDEX "co_deployments_site_id" ON "co_deployments" ("site_id");
-- Create "co_devices" table
CREATE TABLE "co_devices" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "host" character varying NOT NULL,
  "capabilities" bytea NOT NULL,
  "site_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "co_devices_co_sites_devices" FOREIGN KEY ("site_id") REFERENCES "co_sites" ("id") ON DELETE NO ACTION
);
-- Create index "co_devices_site_id_host" to table: "co_devices"
CREATE UNIQUE INDEX "co_devices_site_id_host" ON "co_devices" ("site_id", "host");
-- Create "co_publications" table
CREATE TABLE "co_publications" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "bundle" boolean NOT NULL,
  "deployment_id" uuid NOT NULL,
  "digest" character varying NOT NULL,
  "site_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "co_publications_co_sites_publications" FOREIGN KEY ("site_id") REFERENCES "co_sites" ("id") ON DELETE NO ACTION
);
-- Create index "co_publications_key" to table: "co_publications"
CREATE UNIQUE INDEX "co_publications_key" ON "co_publications" ("site_id", "bundle", "deployment_id", "digest");
-- Create "co_statuses" table
CREATE TABLE "co_statuses" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "status" bytea NOT NULL,
  "deployment_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "co_statuses_co_deployments_statuses" FOREIGN KEY ("deployment_id") REFERENCES "co_deployments" ("id") ON DELETE NO ACTION
);
-- Create index "co_statuses_deployment_id" to table: "co_statuses"
CREATE INDEX "co_statuses_deployment_id" ON "co_statuses" ("deployment_id");

-- SPEC §12: a site's manifestVersion never decreases.
CREATE FUNCTION "co_sites_manifest_version_never_decreases"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.manifest_version < OLD.manifest_version THEN
    RAISE EXCEPTION 'site %: manifest_version % is below the current %',
      OLD.id, NEW.manifest_version, OLD.manifest_version USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END
$$;
CREATE TRIGGER "co_sites_manifest_version_never_decreases"
  BEFORE UPDATE OF "manifest_version" ON "co_sites"
  FOR EACH ROW EXECUTE FUNCTION "co_sites_manifest_version_never_decreases"();
